import { useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { Archive, ArrowRight, BadgeCheck, BookOpen, ChevronDown, FileCheck2, Heart, Map, Package, Plus, ShoppingBag, Users, Video, Wallet } from 'lucide-react'
import { photos, type ProductListing, type Role } from '../data'
import { AdminConsole } from './AdminConsole'
import { CurtainMedia } from '../components/CurtainMedia'

export function Dashboard({ role, onAddProduct, setScreen, setQuery, products }: { role: Role; onAddProduct: () => void; setScreen: (screen: 'feed'|'dashboard'|'marketplace'|'map'|'archive') => void; setQuery: (query: string) => void; products: ProductListing[] }) {
  const [action,setAction]=useState('')
  const content = role === 'Artisan' ? <ArtisanDashboard onAddProduct={onAddProduct} products={products}/> : role === 'Explorer' ? <ExplorerDashboard setScreen={setScreen}/> : role === 'Student / Researcher' ? <ResearchDashboard setScreen={setScreen} setQuery={setQuery}/> : role === 'Expert / Evaluator' || role === 'Cultural Knowledge Holder' ? <CommunityReviewDashboard setScreen={setScreen}/> : role === 'Institution / NGO' ? <><CommunityGroupPageManager notify={setAction}/><InstitutionDashboard notify={setAction}/></> : <AdminConsole notify={setAction}/>
  return <>{content}{action&&<div className="fixed inset-0 z-[75] flex items-center justify-center bg-[#211d19]/55 p-4" onClick={()=>setAction('')}><section role="dialog" aria-modal="true" aria-labelledby="workspace-action-title" onClick={event=>event.stopPropagation()} className="sari-dialog w-full max-w-lg rounded-3xl p-6"><p className="craft-overline text-xs">ASTITVA SAMPLE WORKSPACE</p><h3 id="workspace-action-title" className="mt-2 font-serif text-2xl">{action}</h3><p className="mt-3 text-sm leading-6 text-[#675b50]">The related sample records are available in this dashboard. This preview keeps review notes and actions on this device; it does not send requests to an institution or change a live account.</p><button onClick={()=>setAction('')} className="mt-5 w-full rounded-full bg-rust py-3 text-sm font-semibold text-white">Return to dashboard</button></section></div>}</>
}

export function PageIntro({ eyebrow, title, subtitle, action, onAction }: { eyebrow: string; title: string; subtitle: string; action: string; onAction: () => void }) { return <div className="sari-page-heading mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[9px] font-bold tracking-[.18em] text-[#a48766]">{eyebrow}</p><h2 className="mt-1 font-serif text-[28px]">{title}</h2><p className="mt-1 text-[11px] text-[#82766a]">{subtitle}</p></div><button onClick={onAction} className="flex items-center gap-2 rounded-full bg-rust px-4 py-2.5 text-[10px] font-semibold text-white"><Plus size={14}/>{action}</button></div> }
export function Kpi({ label, value, change, icon: Icon }: { label: string; value: string; change: string; icon: typeof Wallet }) { return <div className="sari-panel rounded-2xl border border-[#e9e3d9] bg-white p-4 sm:p-5"><div className="flex items-start justify-between"><p className="text-[10px] text-[#817568]">{label}</p><span className="rounded-lg bg-[#f3eee5] p-2 text-[#95714d]"><Icon size={15}/></span></div><p className="mt-3 font-serif text-[25px]">{value}</p><p className="mt-1 text-[9px] text-[#71805c]">{change}</p></div> }
export function Chart({ title, subtitle }: { title: string; subtitle: string }) { const [period, setPeriod] = useState<'30 days'|'7 days'>('30 days'); const bars = period === '30 days' ? [38, 52, 43, 69, 55, 76, 63, 88, 67, 96, 74, 100] : [48, 62, 54, 70, 60, 84, 100]; return <section className="sari-panel rounded-2xl border border-[#e9e3d9] bg-white p-5"><div className="flex items-start justify-between"><div><h3 className="font-serif text-[18px]">{title}</h3><p className="mt-1 text-[9px] text-muted">{subtitle}</p></div><button aria-label={`Change chart period, currently last ${period}`} onClick={()=>setPeriod(period==='30 days'?'7 days':'30 days')} className="rounded-lg border border-[#ece5da] px-2.5 py-1.5 text-[9px] text-[#74675a]">Last {period} <ChevronDown className="ml-1 inline" size={11}/></button></div><div className="mt-6 flex h-32 items-end gap-2 border-b border-[#eee8de] px-1">{bars.map((height, index) => <div key={index} className="group relative flex flex-1 justify-center"><span style={{ height: `${height}%` }} className={`w-full max-w-8 rounded-t-md ${index === bars.length - 1 ? 'bg-rust' : 'bg-[#d7c6ad]'}`}/></div>)}</div><div className="mt-2 flex justify-between text-[8px] text-[#a39789]"><span>{period==='30 days'?'Sep 01':'Sep 23'}</span><span>{period==='30 days'?'Sep 08':'Sep 25'}</span><span>{period==='30 days'?'Sep 15':'Sep 27'}</span><span>{period==='30 days'?'Sep 22':'Sep 30'}</span></div></section> }
export function Panel({ title, label, children, action }: { title: string; label?: string; children: ReactNode; action?: string }) { const [expanded,setExpanded]=useState(false); return <section className="sari-panel rounded-2xl border border-[#e9e3d9] bg-white p-5"><div className="mb-4 flex items-start justify-between"><div>{label && <p className="mb-1 text-[8px] font-bold tracking-[.16em] text-[#a48766]">{label}</p>}<h3 className="font-serif text-[18px]">{title}</h3></div>{action && <button aria-expanded={expanded} onClick={()=>setExpanded(!expanded)} className="text-[9px] font-semibold text-rust">{expanded?'Close':' '+action} <ArrowRight className="ml-1 inline" size={11}/></button>}</div>{children}{expanded&&<div className="mt-3 rounded-xl border border-[#eadcb9] bg-[#faf4e5] p-4" role="region"><p className="text-sm font-semibold">{action}</p><p className="mt-1 text-sm leading-5 text-[#675b50]">{panelActionHelp(action || '',title)}</p></div>}</section> }
function panelActionHelp(action: string,title: string) { if(action.toLowerCase().includes('catalog')) return 'Your current maker listings are shown above. Use “Add a product” to create a new local demo listing.'; if(action.toLowerCase().includes('receipt')) return 'The sample order list above includes maker, order number and delivery status. No payment or shipment is processed in this preview.'; if(action.toLowerCase().includes('export')) return 'Citation records in the Research Archive can be downloaded as a CSV file.'; if(action.toLowerCase().includes('trail')) return 'This sample trail is a draft. Review the listed stops and maker consent before treating it as a published itinerary.'; if(action.toLowerCase().includes('queue')) return 'The items shown above are sample moderation records. A live review queue requires the Astitva service.'; return `${title} is showing sample workspace data. This action opens the related records displayed in this section; live account changes need the Astitva service.` }
export function Row({ title, detail, badge, image }: { title: string; detail: string; badge?: string; image?: string }) { return <div className="flex items-center gap-3 border-b border-[#f0ebe3] py-3 last:border-0"><div className="flex h-9 w-9 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-[#f2ede4] text-[#8b704d]">{image ? <CurtainMedia className="h-full w-full rounded-xl" label={title}><img src={image} alt="" className="h-full w-full object-cover"/></CurtainMedia> : <FileCheck2 size={15}/>}</div><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-semibold">{title}</p><p className="mt-0.5 truncate text-[9px] text-muted">{detail}</p></div>{badge && <span className="rounded-full bg-[#f1eee7] px-2 py-1 text-[8px] text-[#78684f]">{badge}</span>}</div> }
function ArtisanDashboard({ onAddProduct, products }: { onAddProduct: () => void; products: ProductListing[] }) { return <><PageIntro eyebrow="ARTISAN WORKSPACE" title="Good morning, Mira." subtitle="Your craft is reaching new people. Here is your studio at a glance." action="Add a product" onAction={onAddProduct}/><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Kpi label="Post & reel views" value="18.4k" change="↑ 14.2% this month" icon={Video}/><Kpi label="Product sales" value="₹42,800" change="↑ 8 orders this month" icon={ShoppingBag}/><Kpi label="Reel engagement" value="8.6%" change="↑ 2.1% vs last month" icon={Heart}/><Kpi label="Available earnings" value="₹31,250" change="3 orders in transit" icon={Wallet}/></div><div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-[1.35fr_1fr]"><Chart title="Your community is growing" subtitle="Views and meaningful interactions · past 30 days"/><Panel title="Verification progress" label="HERITAGE CLAIM · AJRAKH PRINTING"><div className="flex items-center justify-between text-[9px] text-[#807568]"><span>Expert review</span><span>2 of 3 stages</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#eee9df]"><div className="h-full w-2/3 rounded-full bg-olive"/></div><div className="mt-4 space-y-2"><Row title="Claim submitted" detail="Sep 12 · Provenance documents received" badge="Done"/><Row title="AI & registry match" detail="GI reference and location checked" badge="Done"/><Row title="Regional expert review" detail="Assigned to handloom evaluator" badge="In review"/></div></Panel></div><div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-2"><Panel title="Catalog & inventory" label={`${products.length} ACTIVE LISTINGS`} action="Manage catalog">{products.slice(0,3).map(product=><Row key={product.id} title={product.title} detail={`₹${Number(product.price).toLocaleString('en-IN')} · ${product.craft}`} badge={product.stock} image={product.image}/>)}</Panel><Panel title="Orders to fulfill" label="ORDERS & MESSAGES" action="View all orders"><Row title="Order #AS-2048" detail="Neha S. · Ship by 02 Oct" badge="Pack order"/><Row title="Custom request" detail="Ravi K. · Indigo table runner" badge="Reply"/></Panel></div></> }
function ExplorerDashboard({ setScreen }: { setScreen: (screen: 'feed'|'dashboard'|'marketplace'|'map'|'archive') => void }) { return <><PageIntro eyebrow="CULTURE EXPLORER WORKSPACE" title="Your culture passport." subtitle="See the makers you support, your orders, and the traditions you have discovered." action="Explore the feed" onAction={() => setScreen('feed')}/><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Kpi label="Artisans supported" value="12" change="Across 5 regions" icon={Users}/><Kpi label="Craft purchases" value="4" change="All maker-direct" icon={ShoppingBag}/><Kpi label="Impact contribution" value="₹18,400" change="Paid to local makers" icon={Heart}/><Kpi label="Passport badges" value="7" change="2 new this season" icon={BadgeCheck}/></div><div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-[1.2fr_1fr]"><Panel title="Your active orders" label="ORDER HISTORY & TRACKING" action="See receipts"><Row title="Ajrakh Indigo Stole" detail="Mira Vankar · Order #AS-2048" badge="In transit" image={photos.indigo}/><div className="ml-12 mt-1 h-1 rounded-full bg-[#eee9df]"><div className="h-full w-2/3 rounded-full bg-olive"/></div><p className="ml-12 mt-1 text-[8px] text-muted">Shipped from Kutch · Est. delivery Oct 02</p><Row title="Blue pottery serving bowl" detail="Raghav Kumhar · Order #AS-1982" badge="Delivered" image={photos.pottery}/></Panel><Panel title="Your heritage passport" label="IMPACT & BADGES"><div className="grid grid-cols-3 gap-2">{[['✳','First maker'],['⌂','Kutch explorer'],['❋','Indigo admirer']].map(([icon,name])=><div key={name} className="rounded-xl bg-[#f7f4ed] p-3 text-center"><span className="mx-auto flex h-8 w-8 items-center justify-center rounded-full bg-[#e9dfce] text-[#8c613d]">{icon}</span><p className="mt-2 text-[8px] font-semibold">{name}</p></div>)}</div><p className="mt-4 text-[9px] leading-5 text-[#82766a]">Your purchases support living craft traditions and the people who carry them forward.</p></Panel></div><div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-2"><Chart title="Your local impact" subtitle="Maker-direct spend by month"/><Panel title="Messages with makers" label="DIRECT CONNECTION"><Row title="Mira Vankar" detail="Your custom color request is ready" badge="New reply" image={photos.mira}/><Row title="Raghav Kumhar" detail="Care instructions for your bowl" badge="Yesterday" image={photos.portrait1}/></Panel></div></> }
function ResearchDashboard({ setScreen, setQuery }: { setScreen: (screen: 'feed'|'dashboard'|'marketplace'|'map'|'archive') => void; setQuery: (query: string) => void }) { return <><PageIntro eyebrow="STUDENT & RESEARCHER WORKSPACE" title="Research with care and provenance." subtitle="Draft a meaningful paper with a research question, method, cited sources, location and community consent." action="Open research studio" onAction={()=>{setQuery('');setScreen('archive')}}/><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Kpi label="Citable records" value="38" change="Across 6 craft traditions" icon={BookOpen}/><Kpi label="Research papers" value="Start here" change="Draft and export locally" icon={FileCheck2}/><Kpi label="Regions documented" value="4" change="Place-specific evidence" icon={Map}/><Kpi label="Archive citations" value="21" change="Searchable source records" icon={Archive}/></div><div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-[1.3fr_1fr]"><Panel title="Research questions that can lead somewhere" label="SAMPLE STARTING POINTS"><Row title="How do Ajrakh printers describe a motif’s name and use?" detail="Compare maker accounts with attributed archive records · Dhamadka, Gujarat" badge="Oral history"/><Row title="What changes when a craft vocabulary is translated?" detail="Document original-language terms beside a consented translation" badge="Language"/><Row title="Which parts of a process are taught by demonstration?" detail="Record method, source, date, and permissions before interpretation" badge="Field study"/></Panel><Panel title="A useful paper includes" label="RESEARCH CHECKLIST"><Row title="Focused research question" detail="One place, practice, period or question" badge="Required"/><Row title="Clear method and cited sources" detail="Identify how evidence was gathered and where it came from" badge="Required"/><Row title="Consent, attribution and limits" detail="Respect the contributor’s language, ownership and boundaries" badge="Required"/><button onClick={()=>{setQuery('');setScreen('archive')}} className="mt-3 text-sm font-semibold text-rust">Open archive and paper notebook <ArrowRight className="ml-1 inline" size={14}/></button></Panel></div><StudentMissions/></> }

const missions=[{id:'ajrak',title:'Document an Ajrakh motif',place:'Dhamadka, Gujarat',detail:'Ask a printer how one named motif is made and what its name means in the local language.',credit:'Field note certificate'}, {id:'dhokra',title:'Record a Dhokra process',place:'Bastar, Chhattisgarh',detail:'With maker permission, document the stages from wax model to finished metal casting.',credit:'Oral history certificate'}, {id:'blue-pottery',title:'Map a blue pottery vocabulary',place:'Jaipur, Rajasthan',detail:'Collect three maker-approved terms for materials or firing and cite the contributor.',credit:'Language documentation certificate'}]
function StudentMissions(){const [adminMissions]=useState(()=>{try{return JSON.parse(localStorage.getItem("astitva-admin-missions")||"[]") as Array<{title:string;place:string;credit:string}>}catch{return []}});const allMissions=[...missions,...adminMissions.map((mission,index)=>({...mission,id:"institution-"+index,detail:"Institution-posted documentation task. Follow contributor consent and cite sources."}))];const [state,setState]=useState<Record<string,'started'|'completed'>>(()=>{try{return JSON.parse(localStorage.getItem('astitva-student-missions')||'{}') as Record<string,'started'|'completed'>}catch{return {}}});const advance=(id:string)=>{const next:Record<string,'started'|'completed'>={...state,[id]:state[id]==='started'?'completed':'started'};setState(next);try{localStorage.setItem('astitva-student-missions',JSON.stringify(next))}catch{}};const certificate=(mission:typeof missions[number])=>{const body=`ASTITVA · STUDENT MISSION CERTIFICATE\n\nAwarded for completing: ${mission.title}\nPlace: ${mission.place}\nDate: ${new Date().toLocaleDateString('en-IN')}\n\nThis demo certificate records completion of a community-centered documentation mission. It is not an institution-issued academic credit.`;const url=URL.createObjectURL(new Blob([body],{type:'text/plain'}));const link=document.createElement('a');link.href=url;link.download=`astitva-${mission.id}-certificate.txt`;link.click();URL.revokeObjectURL(url)};return <section className="mt-5"><div className="mb-3"><p className="craft-overline text-xs">STUDENT MISSIONS · SAMPLE INSTITUTION TASKS</p><h3 className="mt-1 font-serif text-2xl">Learn by documenting with care.</h3><p className="mt-1 text-sm text-[#756b5e]">Missions are for Student / Researcher accounts. Follow local consent and attribution; completed demo missions earn a downloadable portfolio certificate.</p></div><div className="grid gap-3 lg:grid-cols-3">{allMissions.map(mission=><article key={mission.id} className="sari-panel rounded-2xl border border-[#e9e3d9] bg-white p-4"><p className="text-xs font-semibold text-olive">{mission.place}</p><h4 className="mt-1 font-serif text-lg">{mission.title}</h4><p className="mt-2 text-sm leading-5 text-[#675b50]">{mission.detail}</p><div className="mt-4 flex flex-wrap gap-2">{state[mission.id]==='completed'?<><span className="rounded-full bg-[#edf0e7] px-3 py-2 text-xs font-bold text-olive">Mission complete</span><button onClick={()=>certificate(mission)} className="rounded-full border border-[#d9c798] px-3 py-2 text-xs font-semibold">Download certificate</button></>:<button onClick={()=>advance(mission.id)} className="rounded-full bg-rust px-4 py-2.5 text-sm font-bold text-white">{state[mission.id]==='started'?'Submit field note & complete':'Start mission'}</button>}</div><p className="mt-2 text-xs text-[#817568]">{mission.credit}</p></article>)}</div></section>}

function CommunityReviewDashboard({setScreen}:{setScreen:(screen:'feed'|'dashboard'|'marketplace'|'map'|'archive')=>void}) { return <><PageIntro eyebrow="COMMUNITY KNOWLEDGE STEWARDS" title="Review claims with local context." subtitle="Read the source, language and evidence before voting. Each claim needs two independent eligible reviewers for a decision." action="Review heritage claims" onAction={()=>setScreen('feed')}/><div className="grid gap-4 md:grid-cols-2"><Panel title="Your role" label="COMMUNITY REVIEW"><p className="text-sm leading-6 text-[#675b50]">Knowledge holders and verified experts can support a claim, ask for more context, or dispute it with evidence. Votes are attached to your reviewer profile; ordinary posts do not require verification.</p><button onClick={()=>setScreen('feed')} className="mt-4 rounded-full bg-olive px-4 py-2.5 text-sm font-bold text-white">Open claims in the feed</button></Panel><Panel title="Respect language and lived knowledge" label="REVIEW GUIDANCE"><Row title="Check who shared it" detail="Prefer first-hand community knowledge and cited sources" badge="Source"/><Row title="Keep dialect context" detail="Ask for translation context without erasing original terms" badge="Language"/><Row title="Use evidence, not popularity" detail="A claim becomes reviewed only after two eligible reviewers agree" badge="Process"/></Panel></div></> }
function InstitutionDashboard({ notify }: { notify: (value: string) => void }) { return <><PageIntro eyebrow="INSTITUTIONAL PARTNER WORKSPACE" title="Kutch artisan network." subtitle="Onboard makers, follow regional impact, and build community-led heritage trails." action="Onboard artisans" onAction={() => notify('Bulk onboarding opened')}/><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Kpi label="Artisans onboarded" value="184" change="↑ 12 this quarter" icon={Users}/><Kpi label="Active listings" value="76" change="Across 9 craft groups" icon={Package}/><Kpi label="Regional sales" value="₹8.2L" change="↑ 18% this quarter" icon={Wallet}/><Kpi label="Documentation coverage" value="68%" change="4 target districts" icon={Map}/></div><div className="mt-4 grid grid-cols-1 gap-4 xl:grid-cols-[1.3fr_1fr]"><Chart title="Cluster economic impact" subtitle="Maker-direct sales across the region"/><Panel title="District coverage" label="LIVING DOCUMENTATION"><Row title="Bhujodi" detail="Handloom · 42 makers · 81% documented" badge="Strong"/><Row title="Dhamadka" detail="Ajrakh · 31 makers · 72% documented" badge="Growing"/><Row title="Nirona" detail="Rogan & lacquer · 18 makers · 46% documented" badge="Support"/></Panel></div><div className="mt-4 grid grid-cols-1 gap-4 lg:grid-cols-2"><Panel title="Sponsored heritage trail" label="CAMPAIGN IN PROGRESS" action="Edit trail"><Row title="Indigo routes of Kutch" detail="6 maker stops · 2-day visitor route" badge="Draft" image={photos.indigo}/><p className="text-[9px] leading-5 text-[#817568]">Local maker consent and accessibility information are required before publishing.</p></Panel><Panel title="Community roster" label="ARTISAN GROUPS" action="View roster"><Row title="Vankar weaving collective" detail="42 artisans · 16 active products" badge="Active" image={photos.loom}/><Row title="Dhamadka Ajrakh printers" detail="31 artisans · 12 active products" badge="Active" image={photos.indigo}/></Panel></div></> }

type CommunityGroupPage = { id: string; name: string; tradition: string; place: string; description: string; managers: string[] }

function isCommunityGroupPage(value: unknown): value is CommunityGroupPage {
  if (!value || typeof value !== 'object') return false
  const page = value as Record<string, unknown>
  return typeof page.id === 'string'
    && typeof page.name === 'string'
    && typeof page.tradition === 'string'
    && typeof page.place === 'string'
    && typeof page.description === 'string'
    && Array.isArray(page.managers)
    && page.managers.every(manager => typeof manager === 'string')
}

function CommunityGroupPageManager({ notify }: { notify: (value: string) => void }) {
  const [pages, setPages] = useState<CommunityGroupPage[]>(() => {
    try {
      const stored = localStorage.getItem('astitva-community-pages')
      if (!stored) return []
      const parsed: unknown = JSON.parse(stored)
      if (!Array.isArray(parsed) || !parsed.every(isCommunityGroupPage)) throw new Error('Invalid community page data')
      return parsed
    } catch {
      window.setTimeout(() => notify('Saved community pages could not be loaded because their browser data is unavailable or invalid.'), 0)
      return []
    }
  })
  const [open, setOpen] = useState(false)
  const [name, setName] = useState('')
  const [tradition, setTradition] = useState('')
  const [place, setPlace] = useState('')
  const [description, setDescription] = useState('')
  const [managers, setManagers] = useState('')

  const createPage = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const managerEmails = managers.split(/[,\n]/).map(item => item.trim()).filter(Boolean)
    if (!managerEmails.length || managerEmails.some(email => !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))) {
      notify('Enter one or more valid manager email addresses, separated by commas or new lines.')
      return
    }
    const page: CommunityGroupPage = {
      id: `community-page-${Date.now()}`,
      name: name.trim(),
      tradition: tradition.trim(),
      place: place.trim(),
      description: description.trim(),
      managers: managerEmails,
    }
    const next = [page, ...pages]
    try {
      localStorage.setItem('astitva-community-pages', JSON.stringify(next))
    } catch {
      notify('Could not save the group page because browser storage is full. Free space and try again.')
      return
    }
    setPages(next)
    setOpen(false)
    setName('')
    setTradition('')
    setPlace('')
    setDescription('')
    setManagers('')
    notify('Shared community page created on this device')
  }

  return <section className="sari-panel mb-4 rounded-2xl border bg-white p-5">
    <div className="flex flex-wrap items-start justify-between gap-3">
      <div><p className="craft-overline text-xs">SHARED COMMUNITY PAGES</p><h3 className="mt-1 font-serif text-xl">One page, managed by your group</h3><p className="mt-1 max-w-2xl text-sm leading-5 text-[#675b50]">Represent an organisation or cultural group collectively. Add multiple page managers instead of linking to an individual social profile.</p></div>
      <button type="button" onClick={() => setOpen(!open)} className="rounded-full bg-rust px-4 py-2.5 text-sm font-semibold text-white">{open ? 'Close form' : 'Create group page'}</button>
    </div>
    {open && <form onSubmit={createPage} className="mt-4 grid gap-3 rounded-xl bg-[#faf4e5] p-4 sm:grid-cols-2">
      <label className="text-sm font-semibold">Group or organisation name<input required maxLength={90} value={name} onChange={event => setName(event.target.value)} className="form-control mt-1" placeholder="e.g. Bhujodi Weavers Collective"/></label>
      <label className="text-sm font-semibold">Heritage tradition<input required maxLength={90} value={tradition} onChange={event => setTradition(event.target.value)} className="form-control mt-1" placeholder="e.g. Vankar handloom"/></label>
      <label className="text-sm font-semibold">Place / region<input required maxLength={120} value={place} onChange={event => setPlace(event.target.value)} className="form-control mt-1" placeholder="Village, district and state"/></label>
      <label className="text-sm font-semibold">Page managers <span className="font-normal text-[#756b5e]">(emails, separated by commas or new lines)</span><textarea required rows={2} value={managers} onChange={event => setManagers(event.target.value)} className="form-control mt-1" placeholder="team@example.org, steward@example.org"/></label>
      <label className="text-sm font-semibold sm:col-span-2">About this community page<textarea required minLength={20} maxLength={600} rows={3} value={description} onChange={event => setDescription(event.target.value)} className="form-control mt-1" placeholder="Share the group’s heritage work, community priorities and what visitors can learn."/></label>
      <div className="flex flex-wrap gap-2 sm:col-span-2"><button type="submit" className="rounded-full bg-rust px-5 py-2.5 text-sm font-semibold text-white">Create shared page</button><button type="button" onClick={() => setOpen(false)} className="rounded-full border border-[#d8c48f] px-5 py-2.5 text-sm font-semibold">Cancel</button></div>
    </form>}
    {pages.length > 0 ? <div className="mt-4 grid gap-3 md:grid-cols-2">{pages.map(page => <article key={page.id} className="rounded-xl border border-[#e8dfd0] bg-white p-4"><p className="text-xs font-bold text-olive">{page.tradition} · {page.place}</p><h4 className="mt-1 font-serif text-lg">{page.name}</h4><p className="mt-2 text-sm leading-5 text-[#675b50]">{page.description}</p><p className="mt-3 text-xs text-[#756b5e]">Managed by {page.managers.length} group {page.managers.length === 1 ? 'member' : 'members'}</p></article>)}</div> : <p className="mt-4 rounded-xl bg-[#f8f3e9] p-3 text-sm text-[#675b50]">Your group’s shared page will appear here after it is created.</p>}
  </section>
}
