import { useState } from 'react'
import { ArrowRight, BadgeCheck, Headphones, Heart, MessageCircle, Mic2, Plus } from 'lucide-react'
import { CurtainMedia } from '../components/CurtainMedia'
import { roleLabel, type CommunityPost, type Profile, type Role, type Screen, photos } from '../data'

export function Feed({ saved, setSaved, notify, onNewPost, communityPosts, setScreen, query, setQuery, profiles, followedIds, onFollow, onOpenProfile, reactions, setReactions, role, canVerify, reviewVotes, onReview }: { saved: boolean; setSaved: (value: boolean) => void; notify: (value: string) => void; onNewPost: () => void; communityPosts: CommunityPost[]; setScreen: (screen: Screen) => void; query: string; setQuery:(query:string)=>void; profiles: Profile[]; followedIds: string[]; onFollow: (id:string)=>void; onOpenProfile:(id:string)=>void; reactions:Record<string,'like'|'dislike'>; setReactions:(value:Record<string,'like'|'dislike'>)=>void; role:Role; canVerify:boolean; reviewVotes:Record<string,Record<string,string>>; onReview:(postId:string,vote:string)=>void }) {
  const [tab, setTab] = useState('For you')
  const [story, setStory] = useState<CommunityPost|null>(null)
  const matches = (value: string) => value.toLowerCase().includes(query.trim().toLowerCase())
  const matchingPosts = communityPosts.filter(post => matches(`${post.caption} ${post.craft} ${post.location} ${post.kind}`))
  const storyPosts=communityPosts.filter(post=>post.kind==='story')
  const showVideo = !query.trim() || matches('Charkha spinning Bengaluru Karnataka video handloom')
  const showAudio = !query.trim() || matches('Dhamadka Gujarat Gujarati audio Doharo verse')
  const tabs = ['For you', 'Video & Reels', 'Stories, Photos & Audio']
  const profileFor=(id:string)=>profiles.find(profile=>profile.id===id)||profiles[0]
  const onReact=(id:string,value:'like'|'dislike')=>{const next={...reactions};if(reactions[id]===value)delete next[id];else next[id]=value;setReactions(next)}
  const sharedProps={notify,profiles,followedIds,onFollow,onOpenProfile,reactions,onReact,canVerify,reviewVotes,onReview,setQuery}
  return <div className="mx-auto grid max-w-[1100px] grid-cols-1 gap-6 xl:grid-cols-[minmax(400px,1fr)_280px]">
    <section className="min-w-0">
      <div className="thread-hero sari-banner relative mb-5 overflow-hidden rounded-[24px] px-5 py-6 sm:px-7 sm:py-7">
        <div className="thread-hero-art absolute inset-y-0 right-0 w-[44%] bg-cover bg-center" role="img" aria-label="A maker at work with a handloom" style={{ backgroundImage: `linear-gradient(90deg,#5b1020 0%,rgba(91,16,32,.15) 88%),url(${photos.loom})` }}/>
        <div className="relative max-w-[560px]"><p className="text-[9px] font-bold tracking-[.2em] text-[#f6c026]">अस्तित्व · A LIVING HERITAGE BOARD</p><h2 className="mt-2 font-serif text-[27px] leading-tight sm:text-[36px]">हर कहानी एक धागे से जुड़ी है</h2><p className="mt-2 max-w-[440px] text-[13px] leading-6 text-white/90">Every story hangs by a thread. Meet the people, places and traditions keeping India's many cultures alive.</p><div className="mt-4 flex flex-wrap items-center gap-2"><span className="rounded-full border border-[#f6c026]/60 bg-[#3a0a14]/40 px-3 py-1.5 text-xs text-[#fff4d5]">Crafts · Music · Food · Festivals</span><span lang="en" className="rounded-full bg-[#f6c026] px-3 py-1.5 text-xs font-bold text-[#3a0a14]">EN · हिंदी · தமிழ்</span></div></div>
        <div className="thread-flower" aria-hidden="true">✿</div><div className="woven-rule absolute inset-x-0 bottom-0"/>
      </div>
      <nav aria-label="Heritage board sections" className="thread-board-links mb-5"><button onClick={()=>setScreen('map')}><span>⌖</span><b>Near you</b><small>Places & routes</small></button><button onClick={()=>setTab('Stories, Photos & Audio')}><span>✿</span><b>Stories</b><small>Voices & memories</small></button><button onClick={()=>setScreen('marketplace')}><span>♧</span><b>Makers</b><small>Meet local hands</small></button><button onClick={()=>setScreen('map')}><span>♢</span><b>Festivals</b><small>Gatherings nearby</small></button></nav>
      <div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="craft-overline text-[9px]">THE LIVING HERITAGE FEED</p><h2 className="mt-1 font-serif text-xl">Many traditions. One shared thread.</h2><p className="mt-1 text-[12px] text-[#f4dfc3]">Stories, sounds and skills shared from communities across India.</p></div><button onClick={onNewPost} className="flex items-center gap-1.5 rounded-full bg-[#f6c026] px-4 py-3 text-[13px] font-bold text-[#3a0a14]"><Plus size={15}/>Share a story</button></div>
      <div className="thread-storyrail mb-4 rounded-2xl p-4"><div className="flex items-center justify-between gap-2"><div><p className="text-sm font-bold">Stories from our people</p><p className="mt-1 text-xs text-[#584234]">A quick doorway into traditions across India.</p></div><button onClick={()=>setTab('Stories, Photos & Audio')} className="text-sm font-bold text-[#7e1c29]">See all</button></div><div className="mt-3 flex gap-3 overflow-x-auto pb-1">{communityPosts.filter(post=>post.kind==='story').map(post=><button key={post.id} onClick={()=>setStory(post)} className="min-w-[92px] text-center"><span className="mx-auto block h-16 w-16 rounded-full bg-gradient-to-tr from-[#a72d45] via-[#e4b84a] to-[#08796f] p-[3px]"><CurtainMedia className="h-full w-full rounded-full" label={post.englishTitle||post.craft}><img src={post.mediaUrl||profileFor(post.authorId).avatar} alt="" className="h-full w-full rounded-full border-2 border-white object-cover"/></CurtainMedia></span><span className="mt-1 block max-w-24 truncate text-xs font-semibold">{post.nativeTitle||profileFor(post.authorId).name.split(' ')[0]}</span></button>)}<button onClick={onNewPost} className="min-w-[92px] text-center"><span className="mx-auto flex h-16 w-16 items-center justify-center rounded-full border-2 border-dashed border-[#bd9852] bg-white text-2xl text-rust">+</span><span className="mt-1 block text-xs font-semibold">Your story</span></button></div></div>
      <div className="story-scroll mb-4 flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="Choose a story type">{tabs.map(item => <button role="tab" aria-selected={tab===item} key={item} onClick={() => setTab(item)} className={`shrink-0 rounded-full px-4 py-2.5 text-sm font-semibold ${tab === item ? 'bg-indigo text-white' : 'border border-[#e3dbcd] bg-white text-[#796d60]'}`}>{item}</button>)}</div>
      {tab==='For you'&&<div className="thread-board-grid">{matchingPosts.map(post=><CommunityPostCard key={post.id} post={post} currentProfileId={profiles.find(profile=>profile.role===role)?.id||'ananya'} {...sharedProps}/>)}{showVideo&&<VideoPost saved={saved} setSaved={setSaved} {...sharedProps}/>}{showAudio&&<AudioPost {...sharedProps}/>}</div>}
      {tab==='Video & Reels'&&<div className="thread-board-grid">{matchingPosts.filter(post=>post.kind==='reel'||post.kind==='video').map(post=><CommunityPostCard key={post.id} post={post} currentProfileId={profiles.find(profile=>profile.role===role)?.id||'ananya'} {...sharedProps}/>)}{showVideo&&<VideoPost saved={saved} setSaved={setSaved} {...sharedProps}/>}</div>}
      {tab==='Stories, Photos & Audio'&&<div className="thread-board-grid">{matchingPosts.filter(post=>post.kind==='story'||post.kind==='photo'||post.kind==='audio').map(post=><CommunityPostCard key={post.id} post={post} currentProfileId={profiles.find(profile=>profile.role===role)?.id||'ananya'} {...sharedProps}/>)}{showAudio&&<AudioPost {...sharedProps}/>}</div>}
      {tab==='For you'&&storyPosts.length>0&&<section className="thread-storyboard mt-8" aria-label="Follow the story thread"><div className="thread-storyboard-title"><span>01 — 02 — 03</span><h3>Follow the story thread</h3><p>From a maker’s hands to the place and people around a tradition.</p></div><div className="thread-storyboard-items">{storyPosts.slice(0,3).map((post,index)=><button key={post.id} onClick={()=>setStory(post)} className="thread-story-frame"><span className="thread-frame-number">0{index+1}</span><CurtainMedia className="thread-story-frame__media curtain-media--window" label={post.englishTitle||post.craft}><img src={post.mediaUrl} alt={`${post.englishTitle||post.craft}, shared from ${post.location}`}/></CurtainMedia><b lang={post.nativeTitle?'hi':undefined}>{post.nativeTitle||post.englishTitle||post.craft}</b><small>{post.location}</small></button>)}</div></section>}
      {query.trim()&&!matchingPosts.length&&!showVideo&&!showAudio&&<div className="rounded-2xl border border-dashed border-[#d8ccba] bg-white p-8 text-center text-sm text-[#81776c]">No stories match “{query}” yet. Clear the search to browse every story.</div>}
    </section>
    <aside className="hidden flex-col gap-4 xl:flex"><div className="sari-panel rounded-2xl border border-[#e9e3d9] bg-white p-5"><p className="text-sm font-bold tracking-[.12em] text-[#80653e]">PEOPLE TO FOLLOW</p>{profiles.filter(profile=>profile.id!==profiles.find(item=>item.role===role)?.id).slice(0,4).map(profile=><div key={profile.id} className="mt-3 flex items-center gap-2"><button onClick={()=>onOpenProfile(profile.id)} className="flex min-w-0 flex-1 items-center gap-2 text-left"><CurtainMedia className="h-10 w-10 shrink-0 rounded-full" label={`${profile.name} profile photo`}><img src={profile.avatar} alt="" className="h-full w-full rounded-full object-cover"/></CurtainMedia><span className="min-w-0"><span className="block truncate text-sm font-bold">{profile.name}</span><span className="block truncate text-xs text-[#756b5e]">{roleLabel(profile.role)}</span></span></button><button aria-label={followedIds.includes(profile.id)?`Unfollow ${profile.name}`:`Follow ${profile.name}`} onClick={()=>onFollow(profile.id)} className="rounded-full border border-[#dfd1bd] px-3 py-2 text-xs font-semibold text-rust">{followedIds.includes(profile.id)?'Following':'Follow'}</button></div>)}<button onClick={()=>onOpenProfile(profiles.find(profile=>profile.role===role)?.id||'ananya')} className="mt-4 text-sm font-bold text-rust">Open my profile <ArrowRight className="ml-1 inline" size={14}/></button><button onClick={() => setScreen('map')} className="mt-3 block text-sm font-bold text-olive">Explore all regions <ArrowRight className="ml-1 inline" size={14}/></button></div><div className="sari-panel rounded-2xl bg-[#f0ebe1] p-5"><p className="text-sm font-bold tracking-[.12em] text-[#80653e]">FIELD NOTE</p><h3 className="mt-2 font-serif text-lg">Indigo, from seed to cloth</h3><p className="mt-1 text-sm leading-5 text-[#665b50]">A community recording of the Doharo poetic metre, with Gujarati audio and source attribution.</p><div className="mt-4 flex items-center gap-3"><CurtainMedia className="h-12 w-12 shrink-0 rounded-xl" label="Indigo textile"><img src={photos.indigo} alt="Indigo textile" className="h-full w-full rounded-xl object-cover"/></CurtainMedia><audio controls preload="none" aria-label="Play Gujarati Doharo audio" className="h-9 min-w-0 flex-1"><source src="https://upload.wikimedia.org/wikipedia/commons/d/d7/Doharo.ogg" type="audio/ogg"/></audio><span className="text-sm text-[#7b6c5b]">Gujarati</span></div></div></aside>
    {story&&<StoryViewer post={story} author={profileFor(story.authorId)} onClose={()=>setStory(null)} onNext={()=>{const index=storyPosts.findIndex(post=>post.id===story.id);setStory(storyPosts[(index+1)%Math.max(storyPosts.length,1)]||null)}}/>}
  </div>
}

function StoryViewer({ post, author, onClose, onNext }: { post:CommunityPost; author:Profile; onClose:()=>void; onNext:()=>void }) { const video=post.mediaType==='video';const audio=post.mediaType==='audio'||post.kind==='audio'; return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-[#211d19]/90 p-4" onClick={onClose}><section role="dialog" aria-modal="true" aria-label={`Story by ${author.name}`} onClick={event=>event.stopPropagation()} className="relative h-[min(82vh,720px)] w-full max-w-[430px] overflow-hidden rounded-3xl bg-[#19151b] text-white shadow-2xl"><div className="absolute left-4 right-4 top-3 z-10 h-1 rounded bg-white/40"><span className="block h-full w-full rounded bg-white"/></div><button onClick={onClose} aria-label="Close story" className="absolute right-3 top-6 z-10 rounded-full bg-black/45 px-3 py-2 text-sm">Close</button><div className="flex h-full items-center justify-center">{video?<CurtainMedia className="h-full w-full" label={`${author.name}'s video story`}><video autoPlay controls playsInline src={post.mediaUrl} className="h-full w-full object-contain"/></CurtainMedia>:audio?<div className="w-full bg-indigo p-8 text-center"><Mic2 className="mx-auto mb-4 text-[#e4be69]" size={36}/><p className="font-serif text-2xl">A voice from {post.location}</p><audio autoPlay controls src={post.mediaUrl} className="mt-6 w-full" aria-label={`Audio story by ${author.name}`}/></div>:<CurtainMedia className="h-full w-full" label={`${author.name}'s story`}><img src={post.mediaUrl||author.avatar} alt={`${author.name}'s story`} className="h-full w-full object-cover"/></CurtainMedia>}</div><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/85 to-transparent p-5 pt-20"><button onClick={()=>onClose()} className="text-left text-sm font-bold">{author.name} · {post.location}</button><p className="mt-2 text-sm leading-6">{post.caption}</p><div className="mt-2 flex flex-wrap gap-2">{post.hashtags.map(tag=><span key={tag} className="text-sm font-semibold text-[#f0d480]">{tag}</span>)}</div></div><button aria-label="Next story" onClick={onNext} className="absolute right-2 top-1/2 rounded-full bg-black/40 px-3 py-4 text-xl">›</button></section></div> }

function VideoPost({ saved, setSaved, notify, profiles, followedIds, onFollow, onOpenProfile, reactions, onReact }: { saved: boolean; setSaved: (value: boolean) => void; notify: (value: string) => void; profiles:Profile[]; followedIds:string[]; onFollow:(id:string)=>void; onOpenProfile:(id:string)=>void; reactions:Record<string,'like'|'dislike'>; onReact:(id:string,value:'like'|'dislike')=>void }) {
  const [commentsOpen, setCommentsOpen] = useState(false)
  const [comment, setComment] = useState('')
  const [comments, setComments] = useState(['The rhythm is so calming. My grandmother used to spin cotton like this.'])
  const [moreOpen, setMoreOpen] = useState(false)
  const share = () => sharePage(notify)
  const creator=profiles.find(profile=>profile.id==='mira')||profiles[0]
  const reaction=reactions['sample-charkha']
  return <article className="thread-card sari-panel mb-5 rounded-2xl border border-[#e9e3d9] bg-white shadow-soft">
    <div className="flex items-center gap-3 px-4 py-3.5"><button onClick={()=>onOpenProfile(creator.id)} aria-label={`Open ${creator.name}'s profile`}><CurtainMedia className="h-11 w-11 rounded-full" label={`${creator.name} profile photo`}><img src={creator.avatar} alt="" className="h-full w-full rounded-full object-cover"/></CurtainMedia></button><div className="min-w-0"><button onClick={()=>onOpenProfile(creator.id)} className="truncate text-left text-sm font-bold">{creator.name} <BadgeCheck size={14} className="ml-1 inline text-olive"/></button><p className="mt-0.5 text-sm text-muted">Charkha spinning · Bengaluru, Karnataka</p></div><button onClick={() => onFollow(creator.id)} aria-pressed={followedIds.includes(creator.id)} className="ml-auto rounded-full border border-[#dfd1bd] px-3 py-2 text-sm font-semibold text-[#815533]">{followedIds.includes(creator.id) ? 'Following' : '+ Follow'}</button><button onClick={() => setMoreOpen(!moreOpen)} aria-expanded={moreOpen} aria-label="More video options" className="p-1 text-muted"><span className="text-lg">···</span></button></div>
    {moreOpen && <div className="mx-4 mb-3 rounded-xl bg-[#f7f2e8] p-3 text-xs text-[#665748]">Source and maker details are shown with this story. <button onClick={share} className="ml-2 font-semibold text-rust">Copy story link</button></div>}
    <div className="relative mx-auto aspect-[9/12] max-h-[590px] w-full overflow-hidden bg-[#30251d] sm:aspect-[9/10]">
      <CurtainMedia className="h-full w-full curtain-media--window" label="charkha spinning video"><video controls playsInline preload="metadata" poster={photos.loom} className="h-full w-full object-cover" aria-label="Short video showing a woman spinning yarn on a charkha in Bengaluru"><source src="https://upload.wikimedia.org/wikipedia/commons/transcoded/0/09/Lady_yarn_in_a_Charkha_in_Bangalore.webm/Lady_yarn_in_a_Charkha_in_Bangalore.webm.360p.mp4" type="video/mp4"/><source src="https://upload.wikimedia.org/wikipedia/commons/0/09/Lady_yarn_in_a_Charkha_in_Bangalore.webm" type="video/webm"/>Your browser does not support the video element.</video></CurtainMedia>
      <div className="pointer-events-none absolute left-4 top-4 rounded-full bg-black/45 px-3 py-1.5 text-[8px] font-bold tracking-[.14em] text-white backdrop-blur">VIDEO · 00:30 · BENGALURU, KARNATAKA</div>
      <div className="pointer-events-none absolute bottom-12 left-4 max-w-[78%] text-white drop-shadow-lg"><p className="font-serif text-2xl">A charkha in motion</p><p className="mt-1 text-[10px]">Spinning handloom yarn · Bengaluru</p></div>
    </div>
    <div className="p-4 sm:p-5"><p className="text-sm leading-6 text-[#675b50]">A woman spins yarn on a charkha at a handloom stall on M.G. Road in Bengaluru. The clip follows the steady rhythm of turning fiber into thread.</p><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-[#f4eee5] px-3 py-1.5 text-xs font-medium text-[#947044]">#Charkha · #Karnataka</span><a href="https://commons.wikimedia.org/wiki/File:Lady_yarn_in_a_Charkha_in_Bangalore.webm" target="_blank" rel="noreferrer" className="rounded-full bg-[#f4eee5] px-3 py-1.5 text-xs font-medium text-[#947044]">Source & licence · CC BY-SA 3.0</a></div><div className="mt-4 flex flex-wrap items-center gap-4 border-t border-[#f0ebe3] pt-3"><button onClick={() => onReact('sample-charkha','like')} aria-pressed={reaction==='like'} className={`flex items-center gap-1.5 text-sm ${reaction === 'like' ? 'text-[#b24f45]' : 'text-[#74675a]'}`}><Heart size={17} fill={reaction==='like'?'currentColor':'none'}/>{reaction==='like'?248:247} Like</button><button onClick={() => onReact('sample-charkha','dislike')} aria-pressed={reaction==='dislike'} className={`text-sm ${reaction==='dislike'?'font-bold text-indigo':'text-[#74675a]'}`}>Dislike</button><button onClick={() => setCommentsOpen(!commentsOpen)} aria-expanded={commentsOpen} className="flex items-center gap-1.5 text-sm text-[#74675a]"><MessageCircle size={15}/>{32 + comments.length} Discuss</button><button onClick={share} className="text-sm text-[#74675a]">↗ Share</button><button onClick={() => { setSaved(!saved); notify(saved ? 'Removed from collection' : 'Saved to your collection') }} aria-pressed={saved} className={`ml-auto flex items-center gap-1.5 text-sm ${saved ? 'font-semibold text-rust' : 'text-[#74675a]'}`}>▣ {saved ? 'Saved' : 'Collect'}</button></div>{commentsOpen && <div className="mt-4 border-t border-[#f0ebe3] pt-3"><p className="mb-2 text-sm font-semibold">Conversation</p>{comments.map((text,i)=><p key={i} className="mb-2 rounded-lg bg-[#f7f3eb] p-2 text-sm text-[#675b50]">{text}</p>)}<form onSubmit={event=>{event.preventDefault();if(comment.trim()){setComments(current=>[...current,comment.trim()]);setComment('')}}} className="flex gap-2"><input value={comment} onChange={event=>setComment(event.target.value)} placeholder="Add a thoughtful comment" className="form-control"/><button className="rounded-full bg-rust px-4 text-sm font-semibold text-white">Post</button></form></div>}</div>
  </article>
}

function AudioPost({ notify, profiles, followedIds, onFollow, onOpenProfile, reactions, onReact }: { notify: (value: string) => void; profiles:Profile[]; followedIds:string[]; onFollow:(id:string)=>void; onOpenProfile:(id:string)=>void; reactions:Record<string,'like'|'dislike'>; onReact:(id:string,value:'like'|'dislike')=>void }) {
  const [commentsOpen, setCommentsOpen] = useState(false)
  const [comment, setComment] = useState('')
  const [comments, setComments] = useState(['Would love to learn more about the metre used here.'])
  const creator=profiles.find(profile=>profile.id==='saira')||profiles[0]
  const reaction=reactions['sample-doharo']
  return <article className="thread-card sari-panel rounded-2xl border border-[#e9e3d9] bg-white shadow-soft"><div className="p-4 sm:p-5"><div className="flex items-center gap-3"><button onClick={()=>onOpenProfile(creator.id)} aria-label={`Open ${creator.name}'s profile`}><CurtainMedia className="h-11 w-11 rounded-full object-cover" label="image"><img src={creator.avatar} alt="" className="h-11 w-11 rounded-full object-cover"/></CurtainMedia></button><div><button onClick={()=>onOpenProfile(creator.id)} className="text-left text-sm font-bold">{creator.name} <BadgeCheck size={14} className="ml-1 inline text-olive"/></button><p className="mt-0.5 text-sm text-muted">Ajrakh printer · Dhamadka, Gujarat</p></div><button onClick={()=>onFollow(creator.id)} aria-pressed={followedIds.includes(creator.id)} className="ml-auto rounded-full border border-[#dfd1bd] px-3 py-2 text-sm font-semibold text-[#815533]">{followedIds.includes(creator.id)?'Following':'Follow'}</button><span className="flex items-center gap-1 rounded-full bg-[#f3eee5] px-2.5 py-1 text-xs font-semibold text-[#896b49]"><Mic2 size={13}/> VOICE NOTE</span></div>
      <div className="mt-4 grid grid-cols-[76px_1fr] gap-4"><CurtainMedia className="h-[76px] w-[76px] rounded-xl object-cover curtain-media--window" label="image"><img src={photos.indigo} alt="Gujarati folk poetry audio" className="h-[76px] w-[76px] rounded-xl object-cover"/></CurtainMedia><div className="min-w-0"><p className="font-serif text-[17px]">Doharo chhand · a Gujarati verse</p><p className="mt-1 text-[9px] text-[#8b7e70]">Community audio · Gujarati · 00:22</p><div className="mt-2 flex items-center gap-2"><Headphones size={13} className="shrink-0 text-[#95714d]"/><audio controls preload="none" className="h-8 w-full max-w-[360px]" aria-label="Gujarati Doharo chhand audio post"><source src="https://upload.wikimedia.org/wikipedia/commons/d/d7/Doharo.ogg" type="audio/ogg"/>Audio is not supported by your browser.</audio></div></div></div>
      <details className="mt-4 rounded-xl bg-[#f8f6f0] px-3 py-2"><summary className="cursor-pointer text-[9px] font-semibold text-[#735a42]">About this recording</summary><p className="mt-2 text-[10px] leading-5 text-[#716559]">A sample of the singing style used for poems written in Doharo Chhand. No translated transcript is attached to the source recording. Audio by Sushant Savla, dedicated to the public domain (CC0).</p></details>
      <div className="mt-3 flex flex-wrap items-center gap-4 border-t border-[#f0ebe3] pt-3"><button aria-pressed={reaction==='like'} onClick={()=>onReact('sample-doharo','like')} className={`flex items-center gap-1 text-sm ${reaction==='like'?'text-rust':'text-[#74675a]'}`}><Heart size={16} fill={reaction==='like'?'currentColor':'none'}/>{reaction==='like'?87:86} Like</button><button aria-pressed={reaction==='dislike'} onClick={()=>onReact('sample-doharo','dislike')} className={`text-sm ${reaction==='dislike'?'font-bold text-indigo':'text-[#74675a]'}`}>Dislike</button><button aria-expanded={commentsOpen} onClick={() => setCommentsOpen(!commentsOpen)} className="flex items-center gap-1 text-sm text-[#74675a]"><MessageCircle size={14}/>{12+comments.length} Discuss</button><button onClick={() => sharePage(notify)} className="ml-auto text-sm text-[#74675a]">↗ Share recording</button></div>
      {commentsOpen && <div className="mt-3 border-t border-[#f0ebe3] pt-3">{comments.map((text,i)=><p key={i} className="mb-2 rounded-lg bg-[#f7f3eb] p-2 text-xs">{text}</p>)}<form onSubmit={event=>{event.preventDefault();if(comment.trim()){setComments(current=>[...current,comment.trim()]);setComment('')}}} className="flex gap-2"><input value={comment} onChange={event=>setComment(event.target.value)} placeholder="Join the conversation" className="form-control"/><button className="rounded-full bg-rust px-4 text-xs text-white">Post</button></form></div>}
    </div></article>
}

export function ImagePlusIcon() { return <span className="text-sm leading-none">▧</span> }

export function CommunityPostCard({ post, notify, profiles, followedIds, onFollow, onOpenProfile, currentProfileId, reactions, onReact, canVerify, reviewVotes, onReview, setQuery }: { post:CommunityPost; notify:(value:string)=>void; profiles:Profile[]; followedIds:string[]; onFollow:(id:string)=>void; onOpenProfile:(id:string)=>void; currentProfileId:string; reactions:Record<string,'like'|'dislike'>; onReact:(id:string,value:'like'|'dislike')=>void; canVerify:boolean; reviewVotes:Record<string,Record<string,string>>; onReview:(postId:string,vote:string)=>void; setQuery:(query:string)=>void }) {
  const author=profiles.find(profile=>profile.id===post.authorId)||profiles[0]
  const votes=Object.values(reviewVotes[post.id]||{})
  const likeCount=12+votes.length+Number(reactions[post.id]==='like')
  const dislikeCount=Number(reactions[post.id]==='dislike')
  const isVideo=post.mediaType==='video'||post.kind==='video'||post.kind==='reel'
  const isAudio=post.mediaType==='audio'||post.kind==='audio'
  const statusText=post.verificationStatus==='verified'?'Community reviewed · verified':post.verificationStatus==='rejected'?'Review disputed':post.verificationStatus==='needs-evidence'?'More local evidence requested':'Awaiting two eligible community reviewers'
  return <article className="thread-card sari-panel mb-4 overflow-hidden rounded-2xl border border-[#e5ddcf] bg-white shadow-soft">
    <div className="flex items-center gap-3 p-4"><button onClick={()=>onOpenProfile(author.id)} aria-label={`Open ${author.name}'s profile`}><CurtainMedia className="h-11 w-11 rounded-full" label={`${author.name} profile photo`}><img src={author.avatar} alt="" className="h-full w-full rounded-full object-cover"/></CurtainMedia></button><div className="min-w-0 flex-1"><button onClick={()=>onOpenProfile(author.id)} className="text-left text-sm font-bold">{author.name}{author.verified&&<BadgeCheck aria-label="Community verified" size={14} className="ml-1 inline text-olive"/>}</button><p className="mt-0.5 text-sm text-[#756b5e]">{roleLabel(author.role)} · {post.location}</p></div>{author.id!==currentProfileId&&<button aria-pressed={followedIds.includes(author.id)} onClick={()=>onFollow(author.id)} className="rounded-full border border-[#dfd1bd] px-3 py-2 text-sm font-semibold text-rust">{followedIds.includes(author.id)?'Following':'Follow'}</button>}<span className="rounded-full bg-[#f3eee4] px-3 py-1.5 text-xs font-semibold capitalize text-[#796448]">{post.kind}</span></div>
    <div className="thread-arch max-h-[540px] overflow-hidden bg-[#30251d]">{isVideo?<CurtainMedia className="h-full w-full curtain-media--window" label={`${post.kind} by ${author.name}`}><video src={post.mediaUrl} controls playsInline className="h-full w-full object-contain" aria-label={`${post.kind} by ${author.name}`}/></CurtainMedia>:isAudio?<div className="flex min-h-[150px] items-center justify-center gap-4 bg-indigo p-6 text-white"><Mic2 size={24} className="text-[#e4be69]"/><audio src={post.mediaUrl} controls className="w-full max-w-[440px]" aria-label={`Audio post by ${author.name}`}/></div>:post.mediaUrl?<CurtainMedia className="h-full w-full curtain-media--window" label={`${author.name}'s photo`}><img src={post.mediaUrl} alt={post.caption} className="h-full w-full object-cover"/></CurtainMedia>:<div className="flex min-h-[190px] items-center justify-center p-6 text-sm text-white">This upload is stored locally in your browser.</div>}</div>
    <div className="thread-card-copy p-4 sm:p-5">{(post.nativeTitle||post.englishTitle)&&<><h3 className="font-serif text-xl text-[#3a0a14]">{post.nativeTitle||post.englishTitle}</h3><p className="mt-0.5 text-sm font-semibold text-[#815b2c]">{post.englishTitle||post.craft}</p></>}<p className="mt-2 text-sm leading-6 text-[#51483f]">{post.caption}</p><p className="mt-2 text-sm text-[#756b5e]">{post.craft} · {post.location}</p><div className="mt-2 flex flex-wrap gap-x-3 gap-y-1">{post.hashtags.map(tag=><button key={tag} onClick={()=>setQuery(tag)} className="text-sm font-semibold text-olive">{tag}</button>)}</div>
      {post.claimType==='heritage'&&<div className="mt-3 rounded-xl border border-[#e3ce8e] bg-[#fff8df] p-3"><p className="text-sm font-bold">Heritage claim · {statusText}</p><p className="mt-1 text-sm leading-5 text-[#675b50]">{post.evidence||'The contributor has not added a source note.'}</p><p className="mt-2 text-xs text-[#756b5e]">Review votes: {votes.filter(v=>v==='support').length} support · {votes.filter(v=>v==='context').length} ask for context · {votes.filter(v=>v==='dispute').length} dispute</p>{canVerify&&post.verificationStatus==='pending'&&<div className="mt-3 flex flex-wrap gap-2"><button disabled={Boolean(reviewVotes[post.id]?.[currentProfileId])} onClick={()=>onReview(post.id,'support')} className="rounded-full bg-olive px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Support claim</button><button disabled={Boolean(reviewVotes[post.id]?.[currentProfileId])} onClick={()=>onReview(post.id,'context')} className="rounded-full border border-[#bd9852] px-3 py-2 text-xs font-bold disabled:opacity-50">Needs more context</button><button disabled={Boolean(reviewVotes[post.id]?.[currentProfileId])} onClick={()=>onReview(post.id,'dispute')} className="rounded-full border border-[#a74a3b] px-3 py-2 text-xs font-bold text-[#8f3328] disabled:opacity-50">Dispute with evidence</button></div>}{!canVerify&&post.verificationStatus==='pending'&&<p className="mt-2 text-xs text-[#756b5e]">Voting is reserved for community-verified experts and cultural knowledge holders. Everyone can read the claim and its evidence.</p>}</div>}
      <div className="mt-4 flex flex-wrap items-center gap-4 border-t border-[#f0ebe3] pt-3"><button aria-pressed={reactions[post.id]==='like'} onClick={()=>onReact(post.id,'like')} className={`flex items-center gap-1.5 text-sm ${reactions[post.id]==='like'?'text-rust':'text-[#74675a]'}`}><Heart size={17} fill={reactions[post.id]==='like'?'currentColor':'none'}/>{likeCount} Like</button><button aria-pressed={reactions[post.id]==='dislike'} onClick={()=>onReact(post.id,'dislike')} className={`text-sm ${reactions[post.id]==='dislike'?'font-bold text-indigo':'text-[#74675a]'}`}>{dislikeCount} Dislike</button><button onClick={()=>sharePage(notify)} className="ml-auto text-sm text-[#74675a]">↗ Share</button></div>
    </div><span className="thread-bell" aria-hidden="true"/>
  </article>
}

async function sharePage(notify: (message: string) => void) {
  const url = window.location.href
  try { await navigator.clipboard.writeText(url); notify('Story link copied. You can paste it into a message.') }
  catch { window.prompt('Copy this story link', url) }
}
