import { useState } from 'react'
import { ArrowRight, BadgeCheck, Camera, UserRoundPlus, UserRoundCheck } from 'lucide-react'
import { roleLabel, type CommunityPost, type Profile } from '../data'
import { CurtainMedia } from '../components/CurtainMedia'

export function ProfilePage({ current, viewed, followedIds, onFollow, onEdit, posts, onOpenProfile }: { current: Profile; viewed: Profile; followedIds: string[]; onFollow: (id:string)=>void; onEdit: (name:string,bio:string,avatar:string)=>void; posts: CommunityPost[]; onOpenProfile: (id:string)=>void }) {
  const own = current.id === viewed.id
  const [editing,setEditing]=useState(false)
  const [name,setName]=useState(viewed.name)
  const [bio,setBio]=useState(viewed.bio)
  const [avatar,setAvatar]=useState(viewed.avatar)
  const authored=posts.filter(post=>post.authorId===viewed.id)
  const following=followedIds.map(id=>id).filter(id=>id!==viewed.id)
  return <div className="mx-auto max-w-[1050px]">
    <section className="sari-banner relative overflow-hidden rounded-[26px] p-6 text-white sm:p-9"><p className="text-xs font-bold tracking-[.18em] text-[#f0cf7a]">ASTITVA · PEOPLE & STORIES</p><h2 className="mt-2 font-serif text-3xl sm:text-4xl">Every tradition begins with someone.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/85">Meet the people carrying living knowledge, follow their work and hear it in their own words.</p></section>
    <section className="sari-panel -mt-2 grid gap-5 rounded-3xl border border-[#dcc581] bg-white p-5 sm:grid-cols-[170px_1fr] sm:p-7">
      <div className="mx-auto text-center"><CurtainMedia className="mx-auto h-32 w-32 rounded-full border-4 border-[#eddfb9]" label={`${viewed.name} profile photo`}><img src={avatar} alt={`${viewed.name} profile`} className="h-full w-full rounded-full object-cover"/></CurtainMedia><p className="mt-3 text-sm font-bold">{viewed.handle}</p></div>
      <div><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-serif text-3xl">{viewed.name} {viewed.verified&&<BadgeCheck aria-label="Community verified profile" className="inline text-olive" size={20}/>}</h3><p className="mt-1 text-sm text-[#796d60]">{roleLabel(viewed.role)} · {viewed.region}</p></div>{own?<button onClick={()=>setEditing(!editing)} className="rounded-full border border-[#d8c48f] px-4 py-2 text-sm font-semibold">{editing?'Close editor':'Edit profile'}</button>:<button onClick={()=>onFollow(viewed.id)} className="flex items-center gap-2 rounded-full bg-rust px-4 py-2.5 text-sm font-semibold text-white">{followedIds.includes(viewed.id)?<UserRoundCheck size={16}/>:<UserRoundPlus size={16}/>} {followedIds.includes(viewed.id)?'Following':'Follow'}</button>}</div>
        <p className="mt-4 max-w-2xl text-base leading-7 text-[#584e44]">{viewed.bio}</p><p className="mt-2 text-sm text-[#817568]">Speaks: {viewed.language}</p>
        <div className="mt-5 flex flex-wrap gap-8 border-t border-[#eee4cd] pt-4"><p><b className="text-xl">{(viewed.followers+(own?0:followedIds.includes(viewed.id)?1:0)).toLocaleString('en-IN')}</b><span className="ml-2 text-sm text-[#756b5e]">followers</span></p><p><b className="text-xl">{(viewed.following+(own?followedIds.length:0)).toLocaleString('en-IN')}</b><span className="ml-2 text-sm text-[#756b5e]">following</span></p><p><b className="text-xl">{authored.length}</b><span className="ml-2 text-sm text-[#756b5e]">stories</span></p></div>
        {editing&&own&&<form onSubmit={event=>{event.preventDefault();onEdit(name.trim(),bio.trim(),avatar);setEditing(false)}} className="mt-5 grid gap-3 rounded-2xl bg-[#faf4e5] p-4"><label className="text-sm font-semibold">Display name<input required value={name} onChange={e=>setName(e.target.value)} className="form-control mt-1"/></label><label className="text-sm font-semibold">Your story<textarea required rows={3} value={bio} onChange={e=>setBio(e.target.value)} className="form-control mt-1"/></label><label className="flex cursor-pointer items-center gap-2 text-sm font-semibold"><Camera size={16}/> Change profile photo<input type="file" accept="image/*" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file){const reader=new FileReader();reader.onload=()=>setAvatar(String(reader.result));reader.readAsDataURL(file)}}}/></label><button className="w-fit rounded-full bg-rust px-5 py-2.5 text-sm font-semibold text-white">Save profile</button></form>}
      </div>
    </section>
    <section className="mt-7"><div className="flex items-end justify-between"><div><p className="craft-overline text-xs">THE COMMUNITY AROUND US</p><h3 className="mt-1 font-serif text-2xl">{own?'People you follow':'People '+viewed.name+' follows'}</h3></div></div><div className="mt-3 flex gap-3 overflow-x-auto pb-2">{(own?following:[]).map(id=> <ProfileChip key={id} id={id} onOpenProfile={onOpenProfile}/>) }{own&&following.length===0&&<p className="text-sm text-[#756b5e]">Follow makers, storytellers and researchers to keep their new posts in your feed.</p>}{!own&&<p className="text-sm text-[#756b5e]">Following details are private in this demo profile.</p>}</div></section>
    <section className="mt-7"><h3 className="font-serif text-2xl">Stories shared by {own?'you':viewed.name}</h3>{authored.length===0?<div className="mt-3 rounded-2xl border border-dashed border-[#d8ccba] bg-white p-7 text-sm text-[#81776c]">Their stories will appear here when they share with Astitva.</div>:<div className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{authored.map(post=><article key={post.id} className="sari-panel overflow-hidden rounded-2xl border border-[#e4ddcf] bg-white"><div className="h-44 bg-[#efe5cc]">{post.kind==='audio'?<div className="flex h-full items-center justify-center bg-indigo p-5 text-white"><audio controls src={post.mediaUrl}/></div>:post.kind==='video'||post.kind==='reel'?<CurtainMedia className="h-full w-full curtain-media--window" label={`${post.craft} video`}><video controls src={post.mediaUrl} className="h-full w-full object-cover"/></CurtainMedia>:<CurtainMedia className="h-full w-full curtain-media--window" label={post.craft}><img src={post.mediaUrl} alt={post.caption} className="h-full w-full object-cover"/></CurtainMedia>}</div><div className="p-4"><p className="text-sm leading-6">{post.caption}</p><p className="mt-2 text-xs text-[#796d60]">{post.craft} · {post.location}</p><div className="mt-2 flex flex-wrap gap-1">{post.hashtags.map(tag=><span key={tag} className="text-xs font-semibold text-olive">{tag}</span>)}</div></div></article>)}</div>}</section>
  </div>
}

function ProfileChip({ id,onOpenProfile }: { id:string; onOpenProfile:(id:string)=>void }) { const name=id==='mira'?'Mira Vankar':id==='ananya'?'Ananya Rao':id==='aarav'?'Aarav Mehta':id==='saira'?'Saira Bano':id==='ghafur'?'Ghafur Haji':id==='collective'?'Kutch Collective':'Astitva Archive'; const avatar=id==='mira'||id==='ananya'||id==='aarav'||id==='saira'||id==='ghafur'?`https://images.unsplash.com/photo-${id==='mira'?'1531123897727-8f129e1688ce':id==='ananya'?'1500648767791-00dcc994a43e':'1544005313-94ddf0286df2'}?auto=format&fit=crop&w=160&q=80`:'https://images.unsplash.com/photo-1604881988758-f76ad2f7373f?auto=format&fit=crop&w=160&q=80'; return <button onClick={()=>onOpenProfile(id)} className="sari-panel flex min-w-[160px] items-center gap-3 rounded-2xl border bg-white p-3 text-left"><CurtainMedia className="h-11 w-11 shrink-0 rounded-full" label={`${name} profile photo`}><img src={avatar} alt="" className="h-full w-full rounded-full object-cover"/></CurtainMedia><span><span className="block text-sm font-bold">{name}</span><span className="mt-1 flex items-center gap-1 text-xs text-rust">View profile <ArrowRight size={12}/></span></span></button> }
