import { useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { BookOpen, Plus, Download } from 'lucide-react'
import { PageIntro, Panel } from './DashboardPage'

type ArchiveRecord = { title: string; place: string; language: string; kind: string; craft: string; status: string; note: string; source: string }
type ResearchPaper = { id:string; title:string; question:string; abstract:string; method:string; place:string; language:string; citations:string; consent:boolean; updated:string; status:'Draft'|'Ready for review'; domain?:string }
const records: ArchiveRecord[] = [
  { title: 'Natural indigo process', place: 'Dhamadka, Gujarat', language: 'Gujarati', kind: 'Audio transcript', craft: 'Dyeing', status: 'Community reviewed', note: 'A field note on preparing indigo vats and the changing colour of yarn. The record separates maker testimony from editorial context.', source: 'Astitva field archive · sample entry · 2026' },
  { title: 'Vankar weaving motifs', place: 'Kutch, Gujarat', language: 'Gujarati', kind: 'Field video', craft: 'Handloom', status: 'Expert reviewed', note: 'Mira Vankar describes how border motifs are named and passed between generations. Location and contributor consent accompany this sample record.', source: 'Astitva field archive · sample entry · 2026' },
  { title: 'Blue pottery glazing', place: 'Jaipur, Rajasthan', language: 'Hindi', kind: 'Hindi transcript', craft: 'Pottery', status: 'Community reviewed', note: 'A short account of quartz-based bodies, painted motifs and glaze firing, recorded as a community learning resource.', source: 'Astitva field archive · sample entry · 2026' },
  { title: 'Dhokra lost-wax casting', place: 'Bastar, Chhattisgarh', language: 'Hindi', kind: 'Oral history', craft: 'Metalwork', status: 'Needs review', note: 'An oral-history summary describing wax modelling and successive clay layers. The current entry is marked for additional local review.', source: 'Astitva field archive · sample entry · 2026' },
]

export function ResearchArchive({ query, notify }: { query: string; notify: (value: string) => void }) {
  const [craft, setCraft] = useState('All craft categories')
  const [language, setLanguage] = useState('All languages')
  const [verification, setVerification] = useState('All records')
  const [openTitle, setOpenTitle] = useState<string | null>(null)
  const [paperOpen,setPaperOpen]=useState(false)
  const [papers,setPapers]=useState<ResearchPaper[]>(()=>{try{return JSON.parse(localStorage.getItem('astitva-research-papers')||'[]') as ResearchPaper[]}catch{return []}})
  const [paper,setPaper]=useState<ResearchPaper>({id:'',title:'',question:'',abstract:'',method:'Interview',place:'',language:'',citations:'',consent:false,updated:'',status:'Draft',domain:'Craft practice'})
  const filtered = useMemo(() => records.filter(item => {
    const matchesQuery = `${item.title} ${item.place} ${item.language} ${item.kind} ${item.craft} ${item.status} ${item.note}`.toLowerCase().includes(query.toLowerCase())
    return matchesQuery && (craft === 'All craft categories' || item.craft === craft) && (language === 'All languages' || item.language === language) && (verification === 'All records' || item.status === 'Expert reviewed')
  }), [query, craft, language, verification])
  const exportCsv = () => {
    const quote = (value: string) => `"${value.replace(/"/g, '""')}"`
    const csv = [['Title','Place','Language','Format','Craft','Review status','Source'], ...filtered.map(item => [item.title,item.place,item.language,item.kind,item.craft,item.status,item.source])].map(row=>row.map(quote).join(',')).join('\r\n')
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'astitva-heritage-citations.csv'; link.click(); URL.revokeObjectURL(url)
    notify(`Downloaded ${filtered.length} citation ${filtered.length === 1 ? 'record' : 'records'} as CSV`)
  }
  const savePaper=(submit:boolean)=>{
    const saved={...paper,domain:paper.domain||'Craft practice',id:paper.id||`paper-${Date.now()}`,status:submit?'Ready for review' as const:'Draft' as const,updated:new Date().toLocaleDateString('en-IN')}
    const next=[saved,...papers.filter(item=>item.id!==paper.id)]
    let persistenceWarning=''
    try{localStorage.setItem('astitva-research-papers',JSON.stringify(next))}
    catch{persistenceWarning=' Paper is available in this session, but browser storage is full and it may not persist after refresh.'}
    setPapers(next)
    setPaperOpen(false)
    setPaper({id:'',title:'',question:'',abstract:'',method:'Interview',place:'',language:'',citations:'',consent:false,updated:'',status:'Draft',domain:'Craft practice'})
    notify(`${submit?'Paper saved and marked ready for academic review':'Research paper draft saved on this device'}.${persistenceWarning}`)
  }
  const exportPaper=(item:ResearchPaper)=>{const body=`# ${item.title}\n\n**Heritage domain:** ${item.domain||'Craft practice'}  \n**Status:** ${item.status}  \n**Research question:** ${item.question}  \n**Place:** ${item.place}  \n**Language:** ${item.language}  \n**Method:** ${item.method}  \n**Updated:** ${item.updated}\n\n## Abstract\n${item.abstract}\n\n## Sources and citations\n${item.citations}\n\n**Community consent recorded:** ${item.consent?'Yes':'No'}`;const url=URL.createObjectURL(new Blob([body],{type:'text/markdown'}));const link=document.createElement('a');link.href=url;link.download=`${item.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'research-paper'}.md`;link.click();URL.revokeObjectURL(url);notify('Research paper exported as Markdown')}
  return <>
    <PageIntro eyebrow="HERITAGE RESEARCH WORKSPACE" title="Research living heritage with care." subtitle="One place for heritage records, citations and community-conscious research papers." action="New heritage paper" onAction={()=>setPaperOpen(true)}/>
    <section className="mb-5 rounded-2xl border border-[#d9c798] bg-[#fff8e8] p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-bold">Your heritage research papers</p><p className="mt-1 text-sm text-[#756b5e]">Research is scoped to living heritage: craft, oral tradition, language, performance, material culture and place-based knowledge.</p></div><button onClick={()=>setPaperOpen(true)} className="flex items-center gap-2 rounded-full bg-rust px-4 py-3 text-sm font-bold text-white"><Plus size={16}/>Start a paper</button></div>{papers.length===0?<p className="mt-4 rounded-xl bg-white/75 p-4 text-sm text-[#756b5e]">Begin with a heritage question, explain your method, cite your sources and record permission before using community knowledge.</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{papers.map(item=><article key={item.id} className="rounded-xl border border-[#e8dfd0] bg-white p-4"><div className="flex items-start gap-3"><BookOpen className="mt-1 shrink-0 text-olive" size={19}/><div className="min-w-0 flex-1"><h3 className="font-serif text-lg">{item.title}</h3><p className="mt-1 text-sm text-[#756b5e]">{item.domain||'Craft practice'} · {item.place} · {item.method} · Updated {item.updated}</p><p className="mt-2 line-clamp-2 text-sm text-[#675b50]">{item.question}</p><div className="mt-3 flex items-center justify-between"><span className="rounded-full bg-[#f4efe3] px-3 py-1.5 text-xs font-semibold">{item.status}</span><button onClick={()=>exportPaper(item)} className="flex items-center gap-1 text-sm font-semibold text-rust"><Download size={15}/>Export</button></div></div></div></article>)}</div>}</section>
    <div className="grid grid-cols-1 gap-4 xl:grid-cols-[260px_1fr]">
      <Panel title="Archive filters" label="NARROW YOUR SEARCH">
        <label className="mb-3 block text-sm font-semibold">Craft category<select value={craft} onChange={event=>setCraft(event.target.value)} className="form-control mt-2"><option>All craft categories</option><option>Handloom</option><option>Dyeing</option><option>Pottery</option><option>Metalwork</option></select></label>
        <label className="mb-3 block text-sm font-semibold">Language<select value={language} onChange={event=>setLanguage(event.target.value)} className="form-control mt-2"><option>All languages</option><option>Gujarati</option><option>Hindi</option></select></label>
        <label className="mb-3 block text-sm font-semibold">Review status<select value={verification} onChange={event=>setVerification(event.target.value)} className="form-control mt-2"><option>All records</option><option>Expert reviewed</option></select></label>
        <button onClick={()=>{setCraft('All craft categories');setLanguage('All languages');setVerification('All records')}} className="mt-2 rounded-full border border-[#e5d9c8] px-4 py-2 text-sm font-semibold">Clear filters</button>
      </Panel>
      <div><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-[#756b5e]">{filtered.length} matching archive records</p><button onClick={exportCsv} className="flex items-center gap-2 rounded-full border border-[#e5d9c8] bg-white px-4 py-2 text-sm font-semibold text-[#78583a]"><Download size={15}/>Export citations</button></div><Panel title="Living heritage records" label="SEARCH RESULTS · SAMPLE ARCHIVE">
        {filtered.map(item=><article key={item.title} className="border-b border-[#f0ebe3] py-3 last:border-0"><button aria-expanded={openTitle===item.title} onClick={()=>setOpenTitle(openTitle===item.title?null:item.title)} className="flex w-full items-center gap-3 text-left"><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{item.title}</span><span className="mt-1 block text-sm text-[#756b5e]">{item.place} · {item.language} · {item.kind}</span></span><span className="rounded-full bg-[#f1eee7] px-3 py-1.5 text-xs text-[#78684f]">{item.status}</span></button>{openTitle===item.title && <div className="ml-2 mt-3 rounded-xl bg-[#f8f3e9] p-4"><p className="text-sm leading-6 text-[#675b50]">{item.note}</p><p className="mt-2 text-xs text-[#817568]">{item.source}</p></div>}</article>)}
        {filtered.length===0 && <p className="rounded-xl bg-[#f8f3e9] p-5 text-sm text-[#756b5e]">No sample records match these filters. Try another craft, language or search term.</p>}
      </Panel></div>
    </div>
    {paperOpen&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-[#211d19]/65 p-3" onClick={()=>setPaperOpen(false)}><form role="dialog" aria-modal="true" aria-labelledby="paper-title" onClick={event=>event.stopPropagation()} onSubmit={event=>{event.preventDefault();savePaper(false)}} className="max-h-[92vh] w-full max-w-2xl space-y-3 overflow-auto rounded-3xl bg-[#fcfaf4] p-5 shadow-2xl sm:p-7"><div><p className="craft-overline text-xs">RESEARCH NOTEBOOK · LIVING HERITAGE</p><h2 id="paper-title" className="font-serif text-2xl">New heritage research paper</h2><p className="mt-1 text-sm text-[#756b5e]">Choose a heritage domain and capture the question, methods, sources and consent before drawing conclusions.</p></div>
      <Field label="Paper title"><input required value={paper.title} onChange={e=>setPaper({...paper,title:e.target.value})} className="form-control" placeholder="e.g. Naming Ajrakh border motifs in Dhamadka"/></Field><Field label="Research question"><textarea required rows={2} value={paper.question} onChange={e=>setPaper({...paper,question:e.target.value})} className="form-control" placeholder="What specific question will the paper investigate?"/></Field><Field label="Abstract / summary"><textarea required minLength={40} rows={4} value={paper.abstract} onChange={e=>setPaper({...paper,abstract:e.target.value})} className="form-control" placeholder="Summarise scope, context, evidence and intended contribution (at least 40 characters)."/></Field>
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Heritage domain"><select required value={paper.domain||'Craft practice'} onChange={e=>setPaper({...paper,domain:e.target.value})} className="form-control"><option>Craft practice</option><option>Oral tradition</option><option>Language and vocabulary</option><option>Music and performance</option><option>Material culture</option><option>Place-based tradition</option><option>Foodways and ritual practice</option></select></Field><Field label="Method"><select value={paper.method} onChange={e=>setPaper({...paper,method:e.target.value})} className="form-control"><option>Interview</option><option>Oral history</option><option>Participant observation</option><option>Archival study</option><option>Comparative study</option><option>Other documented method</option></select></Field><Field label="Place / region"><input required value={paper.place} onChange={e=>setPaper({...paper,place:e.target.value})} className="form-control" placeholder="Village, district, state"/></Field><Field label="Working language"><input required value={paper.language} onChange={e=>setPaper({...paper,language:e.target.value})} className="form-control" placeholder="Language(s) used in source material"/></Field><Field label="Sources and citations"><textarea required rows={3} value={paper.citations} onChange={e=>setPaper({...paper,citations:e.target.value})} className="form-control" placeholder="Author, title, year, URL or archive reference"/></Field></div>
      <label className="flex items-start gap-3 rounded-xl bg-[#f5efdf] p-3 text-sm leading-5"><input required type="checkbox" checked={paper.consent} onChange={e=>setPaper({...paper,consent:e.target.checked})} className="mt-1 h-4 w-4 accent-[#6d7448]"/><span>I have permission to use any identifiable community contribution included in this paper, and will respect attribution and requested limits.</span></label>
      <div className="flex flex-wrap justify-end gap-2 border-t border-[#e7dfd2] pt-3"><button type="button" onClick={()=>setPaperOpen(false)} className="rounded-full border px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="submit" className="rounded-full border border-[#9e7c50] px-4 py-2.5 text-sm font-semibold text-[#725333]">Save draft</button><button type="button" onClick={()=>{if(!paper.title||!paper.question||paper.abstract.length<40||!paper.place||!paper.language||!paper.citations||!paper.consent){notify('Complete the title, question, 40-character abstract, method details, sources and consent first.');return}savePaper(true)}} className="rounded-full bg-rust px-4 py-2.5 text-sm font-bold text-white">Ready for review</button></div>
    </form></div>}
  </>
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-sm font-semibold">{label}<div className="mt-1.5">{children}</div></label>}
