export type Role = 'Artisan' | 'Explorer' | 'Student / Researcher' | 'Expert / Evaluator' | 'Cultural Knowledge Holder' | 'Institution / NGO' | 'Admin / Moderator'
export type AuthMode = 'login' | 'signup' | 'otp'
export type Screen = 'feed' | 'dashboard' | 'marketplace' | 'map' | 'archive' | 'profile'
export type PostKind = 'reel' | 'story' | 'photo' | 'audio' | 'video'
export type Profile = { id: string; name: string; handle: string; role: Role; bio: string; region: string; language: string; avatar: string; verified: boolean; followers: number; following: number }
export type ProductListing = { id: string; title: string; craft: string; qualities: string; heritage: string; price: string; location: string; stock: string; image: string; maker: string }
export type CommunityPost = { id: string; kind: PostKind; mediaType?: 'image'|'video'|'audio'; mediaKey?: string; caption: string; craft: string; location: string; mediaUrl: string; filename: string; authorId: string; hashtags: string[]; createdAt: string; claimType: 'community' | 'heritage'; evidence?: string; verificationStatus: 'not-required' | 'pending' | 'verified' | 'needs-evidence' | 'rejected'; nativeTitle?: string; englishTitle?: string }

export const roleOptions: Role[] = ['Artisan', 'Explorer', 'Student / Researcher', 'Expert / Evaluator', 'Cultural Knowledge Holder', 'Institution / NGO', 'Admin / Moderator']
export const roleLabel = (role: Role | 'Buyer') => {
  if (role === 'Buyer') return 'Explorer'
  if (role === 'Student / Researcher') return 'Heritage Researcher'
  if (role === 'Expert / Evaluator' || role === 'Cultural Knowledge Holder') return 'Community Reviewer'
  if (role === 'Institution / NGO') return 'Community Organisation'
  return role
}
export const photos = {
  mira: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=160&q=80',
  loom: 'https://images.unsplash.com/photo-1604881988758-f76ad2f7373f?auto=format&fit=crop&w=1200&q=85',
  indigo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=700&q=80',
  pottery: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=700&q=80',
  portrait1: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&q=80',
  portrait2: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&q=80',
}
export const profiles: Profile[] = [
  { id:'mira', name:'Mira Vankar', handle:'@miravankar', role:'Artisan', bio:'Ajrakh printer and natural-dye maker. My family has worked with wooden blocks and indigo in Kutch for generations.', region:'Dhamadka, Kutch · Gujarat', language:'Kutchi · Gujarati', avatar:photos.mira, verified:true, followers:1284, following:286 },
  { id:'ananya', name:'Ananya Rao', handle:'@ananyarao', role:'Explorer', bio:'A curious traveller learning the stories behind the things I bring home.', region:'Bengaluru · Karnataka', language:'Kannada · English', avatar:photos.portrait1, verified:false, followers:418, following:301 },
  { id:'aarav', name:'Aarav Mehta', handle:'@aaravfieldnotes', role:'Student / Researcher', bio:'Graduate researcher documenting community-led craft knowledge with consent and citations.', region:'Ahmedabad · Gujarat', language:'Gujarati · Hindi · English', avatar:photos.portrait2, verified:false, followers:236, following:178 },
  { id:'saira', name:'Saira Bano', handle:'@sairabano', role:'Expert / Evaluator', bio:'Ajrakh practitioner and community-appointed reviewer for Kutch block-printing traditions.', region:'Dhamadka, Kutch · Gujarat', language:'Kutchi · Gujarati · Hindi', avatar:photos.portrait2, verified:true, followers:2093, following:402 },
  { id:'ghafur', name:'Ghafur Haji', handle:'@ghafurji', role:'Cultural Knowledge Holder', bio:'Kutchi storyteller and language keeper. I review names and oral accounts from my community.', region:'Nirona · Kutch · Gujarat', language:'Kutchi · Gujarati', avatar:photos.portrait1, verified:true, followers:875, following:129 },
  { id:'collective', name:'Kutch Craft Collective', handle:'Community page', role:'Institution / NGO', bio:'A community-led network connecting makers, cultural organisations and local visitors.', region:'Bhuj · Gujarat', language:'Gujarati · Hindi', avatar:photos.loom, verified:true, followers:3420, following:617 },
  { id:'archive', name:'Astitva Archive', handle:'@astitvaarchive', role:'Admin / Moderator', bio:'A community archive for living traditions, maker voices and place-based knowledge.', region:'India', language:'Regional languages', avatar:photos.pottery, verified:true, followers:8410, following:51 },
]
export const profileForRole = (role: Role) => profiles.find(profile => profile.role === role) || profiles[1]

export const sampleCommunityPosts: CommunityPost[] = [
  { id:'post-indigo', kind:'photo', nativeTitle:'અજરખની છાપ', englishTitle:'Ajrakh · indigo in layers', caption:'The resist blocks come out before dawn, while the air is still cool. Each layer needs its own drying time.', craft:'Ajrakh printing', location:'Dhamadka, Kutch · Gujarat', mediaUrl:photos.indigo, filename:'indigo-blocks.jpg', authorId:'mira', hashtags:['#Ajrakh','#NaturalDye','#Kutch'], createdAt:'2026-09-29T07:30:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-pottery-story', kind:'story', nativeTitle:'नीली मिट्टी की कहानी', englishTitle:'Blue pottery · Jaipur', caption:'A small studio note: the blue comes from mineral pigments and a careful glaze firing.', craft:'Blue pottery', location:'Jaipur · Rajasthan', mediaUrl:photos.pottery, filename:'jaipur-pottery.jpg', authorId:'collective', hashtags:['#BluePottery','#Jaipur'], createdAt:'2026-09-29T11:10:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-fieldwork', kind:'photo', nativeTitle:'વણકરનું તાણું', englishTitle:'Vankar handloom · Kutch', caption:'Field note: recorded with maker consent. This loom vocabulary is written in Gujarati first, then translated with the speaker.', craft:'Vankar handloom', location:'Bhujodi, Kutch · Gujarat', mediaUrl:photos.loom, filename:'loom-fieldnote.jpg', authorId:'aarav', hashtags:['#FieldNotes','#Handloom','#Gujarati'], createdAt:'2026-09-28T14:15:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-bastar-story', kind:'story', nativeTitle:'ढोकरा शिल्प', englishTitle:'Dhokra · lost-wax casting', caption:'In Bastar, makers shape wax first. The clay mould remembers every line before the metal is poured.', craft:'Dhokra metalwork', location:'Bastar · Chhattisgarh', mediaUrl:'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=700&q=80', filename:'dhokra.jpg', authorId:'ghafur', hashtags:['#Dhokra','#Bastar','#LivingHeritage'], createdAt:'2026-09-28T08:20:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-pattachitra', kind:'photo', nativeTitle:'ପଟ୍ଟଚିତ୍ର', englishTitle:'Pattachitra · painted stories', caption:'A palm-leaf line becomes a river, a forest, a face. Pattachitra artists build each scene with patient brushwork and colours made for the story.', craft:'Pattachitra painting', location:'Raghurajpur · Odisha', mediaUrl:'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=900&q=85', filename:'pattachitra-story.jpg', authorId:'collective', hashtags:['#Pattachitra','#Odisha','#LivingArt'], createdAt:'2026-09-27T10:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-warli', kind:'story', nativeTitle:'वारली चित्रकला', englishTitle:'Warli · stories in white', caption:'Circles gather around the tarpa dance; triangles become people, trees and hills. Warli paintings carry village memory through a language of simple forms.', craft:'Warli painting', location:'Dahanu · Maharashtra', mediaUrl:'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=900&q=85', filename:'warli-painting.jpg', authorId:'ghafur', hashtags:['#Warli','#Maharashtra','#AdivasiArt'], createdAt:'2026-09-26T09:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-phulkari', kind:'photo', nativeTitle:'ਫੁਲਕਾਰੀ', englishTitle:'Phulkari · flowers in thread', caption:'Bright silk floss crosses handwoven khaddar in counted stitches. Each flower is a gift of time, made for a family celebration and worn close to the heart.', craft:'Phulkari embroidery', location:'Patiala · Punjab', mediaUrl:'https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=900&q=85', filename:'phulkari.jpg', authorId:'mira', hashtags:['#Phulkari','#Punjab','#Embroidery'], createdAt:'2026-09-25T12:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-baulsong', kind:'audio', mediaType:'audio', nativeTitle:'বাউল গান', englishTitle:'Baul songs · Bengal', caption:'A travelling song asks what makes a home inside the human heart. This field recording is shared with the singer’s permission; listen with headphones.', craft:'Baul music · oral tradition', location:'Shantiniketan · West Bengal', mediaUrl:'https://upload.wikimedia.org/wikipedia/commons/d/d7/Doharo.ogg', filename:'folk-song-recording.ogg', authorId:'saira', hashtags:['#Baul','#Bengal','#OralTradition'], createdAt:'2026-09-24T08:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-theyyam', kind:'photo', nativeTitle:'തെയ്യം', englishTitle:'Theyyam · ritual performance', caption:'Drums gather the village before the performer appears in a vivid, hand-built crown. The ritual belongs to its local community and is shared here with respect.', craft:'Theyyam performance', location:'Kannur · Kerala', mediaUrl:'https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&w=900&q=85', filename:'theyyam-performance.jpg', authorId:'collective', hashtags:['#Theyyam','#Kerala','#LivingRitual'], createdAt:'2026-09-23T07:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-channapatna', kind:'story', nativeTitle:'ಚನ್ನಪಟ್ಟಣದ ಗೊಂಬೆಗಳು', englishTitle:'Channapatna · lacquer toys', caption:'Turned wood spins against a lac stick, then colour follows the grain. A familiar toy carries the patience of a workshop and the joy of a child.', craft:'Channapatna toy making', location:'Channapatna · Karnataka', mediaUrl:'https://images.unsplash.com/photo-1599623560574-39d485900c95?auto=format&fit=crop&w=900&q=85', filename:'lacquer-toys.jpg', authorId:'collective', hashtags:['#Channapatna','#Karnataka','#ToyMaking'], createdAt:'2026-09-22T11:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-bamboo', kind:'photo', nativeTitle:'बाँस की बुनाई', englishTitle:'Bamboo weaving · Northeast', caption:'Split bamboo becomes a basket through an understanding of tension, moisture and the shape it needs to hold. Makers pass this knowledge hand to hand.', craft:'Bamboo weaving', location:'Majuli · Assam', mediaUrl:'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=900&q=85', filename:'bamboo-weaving.jpg', authorId:'ghafur', hashtags:['#BambooCraft','#Assam','#NortheastIndia'], createdAt:'2026-09-21T06:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
]
export const sampleProducts: ProductListing[] = [
  { id: 'ajrak-1', title: 'Ajrakh indigo stole', craft: 'Block print · Natural dye', qualities: 'Hand block-printed, plant-dyed, breathable cotton', heritage: 'Printed in Dhamadka using resist blocks and indigo knowledge passed through generations.', price: '2400', location: 'Dhamadka, Kutch, Gujarat', stock: '4', image: photos.indigo, maker: 'Mira Vankar' },
  { id: 'pottery-1', title: 'Blue pottery serving bowl', craft: 'Blue pottery · Glazed ceramic', qualities: 'Hand-shaped, mineral pigment, lead-free glaze', heritage: 'Made with Jaipur’s quartz-based blue pottery technique and floral forms from the old city.', price: '1850', location: 'Jaipur, Rajasthan', stock: '8', image: photos.pottery, maker: 'Raghav Kumhar' },
  { id: 'shawl-1', title: 'Kala cotton handwoven shawl', craft: 'Handloom · Kutch', qualities: 'Rain-fed native cotton, naturally textured, handwoven', heritage: 'Woven in Bhujodi with local kala cotton and the Vankar community’s loom practice.', price: '5800', location: 'Bhujodi, Kutch, Gujarat', stock: 'Made to order', image: photos.loom, maker: 'Vankar collective' },
  { id: 'banarasi-1', title: 'Handwoven brocade runner', craft: 'Handloom · Brocade', qualities: 'Silk blend, handloom woven, zari border', heritage: 'A small-format brocade piece woven in Varanasi. Listing is a maker sample, not a claim of GI certification.', price: '3200', location: 'Varanasi, Uttar Pradesh', stock: '3', image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=700&q=80', maker: 'Weaver family collective' },
  { id: 'dhokra-1', title: 'Lost-wax brass diya pair', craft: 'Metalwork · Dhokra', qualities: 'Hand cast, beeswax detailing, brass', heritage: 'A contemporary diya pair made with lost-wax casting knowledge shared by Bastar makers.', price: '1450', location: 'Kondagaon, Bastar, Chhattisgarh', stock: '6', image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=700&q=80', maker: 'Bastar artisan group' },
  { id: 'madurai-1', title: 'Sungudi cotton table cloth', craft: 'Textile · Tie-dye', qualities: 'Cotton, hand-tied dots, natural palette', heritage: 'Sungudi-inspired dotted cotton from a Madurai maker collective; technique and maker details are shared with the listing.', price: '2100', location: 'Madurai, Tamil Nadu', stock: '5', image: 'https://images.unsplash.com/photo-1600100397608-f0107e9a9f7b?auto=format&fit=crop&w=700&q=80', maker: 'Meenakshi textile collective' },
  { id: 'papier-1', title: 'Hand-painted papier-mâché box', craft: 'Papier-mâché · Painting', qualities: 'Paper pulp, hand painted, floral design', heritage: 'A small storage box painted in a Kashmir workshop. The maker describes the preparation and finishing steps.', price: '980', location: 'Srinagar, Jammu and Kashmir', stock: '7', image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=700&q=80', maker: 'Zaina Crafts' },
  { id: 'mask-1', title: 'Satriya performance mask', craft: 'Mask making · Papier-mâché', qualities: 'Paper pulp, natural fibre, hand finished', heritage: 'A performance mask inspired by Majuli’s satra mask-making traditions, described by its maker.', price: '2600', location: 'Majuli, Assam', stock: 'Made to order', image: photos.pottery, maker: 'Majuli mask makers' },
]
