export type Role = 'Artisan' | 'Explorer' | 'Student / Researcher' | 'Expert / Evaluator' | 'Cultural Knowledge Holder' | 'Institution / NGO' | 'Admin / Moderator'
export type AuthMode = 'login' | 'signup' | 'otp'
export type Screen = 'feed' | 'dashboard' | 'marketplace' | 'map' | 'archive' | 'profile'
export type PostKind = 'reel' | 'story' | 'photo' | 'audio' | 'video'
export type Profile = { id: string; name: string; handle: string; role: Role; bio: string; region: string; language: string; avatar: string; verified: boolean; followers: number; following: number }
export type ProductListing = { id: string; title: string; craft: string; qualities: string; heritage: string; price: string; location: string; stock: string; image: string; maker: string }
export type CommunityPost = { id: string; kind: PostKind; mediaType?: 'image'|'video'|'audio'; mediaKey?: string; caption: string; craft: string; location: string; mediaUrl: string; filename: string; authorId: string; hashtags: string[]; createdAt: string; claimType: 'community' | 'heritage'; evidence?: string; verificationStatus: 'not-required' | 'pending' | 'verified' | 'needs-evidence' | 'rejected'; nativeTitle?: string; englishTitle?: string }

export const roleOptions: Role[] = ['Artisan', 'Explorer', 'Student / Researcher', 'Expert / Evaluator', 'Cultural Knowledge Holder', 'Institution / NGO', 'Admin / Moderator']
export const roleLabel = (role: Role | 'Buyer') => {
  if (role === 'Buyer') return 'Explorer'
  if (role === 'Student / Researcher') return 'Heritage Researcher'
  if (role === 'Expert / Evaluator' || role === 'Cultural Knowledge Holder') return 'Community Reviewer'
  if (role === 'Institution / NGO') return 'Community Organisation'
  return role
}
const svgImage = (svg: string) => `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`

function portrait({ skin, hair, garment, accent, style }: { skin: string; hair: string; garment: string; accent: string; style: 'sari' | 'kurta' | 'dupatta' | 'turban' }) {
  const headwear = style === 'turban'
    ? `<path d="M49 64q2-30 31-30t31 30l-7 10H56z" fill="${accent}" stroke="#5b1020" stroke-width="3"/><path d="M51 56q30 11 59 0M57 44q24 12 48 0" fill="none" stroke="#f4d27a" stroke-width="3"/>`
    : `<path d="M47 78q-5-40 33-47 37 3 35 48l-5 17H52z" fill="${hair}"/>`
  const clothing = style === 'sari'
    ? `<path d="M15 180q3-43 44-52l21 13 22-13q41 9 44 52z" fill="${garment}"/><path d="M76 128l31 52H84L66 136M88 132l-8 48h43l-23-53" fill="${accent}" stroke="#f8e4aa" stroke-width="3"/><path d="M50 158h21m-20 9h26m24-18 12 21m-6-27 13 20" stroke="#f8e4aa" stroke-width="2"/>`
    : `<path d="M15 180q4-44 46-52l21 13 22-13q41 8 44 52z" fill="${garment}"/><path d="M61 130l20 13 20-13M80 143v37" fill="none" stroke="${accent}" stroke-width="5"/><path d="M39 158h25m32 0h25" stroke="#f8e4aa" stroke-width="2"/>`
  const jewelry = style === 'sari' || style === 'dupatta'
    ? `<circle cx="80" cy="83" r="3" fill="#c99523"/><path d="M72 112q8 12 16 0" fill="none" stroke="#d8a735" stroke-width="3"/><circle cx="58" cy="95" r="3" fill="#e4bd76"/><circle cx="102" cy="95" r="3" fill="#e4bd76"/>`
    : `<path d="M65 111q15 13 30 0" fill="none" stroke="#d8a735" stroke-width="3"/>`
  return svgImage(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 180"><defs><linearGradient id="bg" x2="1" y2="1"><stop stop-color="#f7e8bd"/><stop offset="1" stop-color="#cf8a55"/></linearGradient><pattern id="weave" width="12" height="12" patternUnits="userSpaceOnUse"><path d="M0 0h12M0 0v12" stroke="#8b1e2d" stroke-opacity=".14" stroke-width="2"/></pattern></defs><rect width="160" height="180" rx="24" fill="url(#bg)"/><rect width="160" height="180" rx="24" fill="url(#weave)"/><circle cx="80" cy="79" r="39" fill="${skin}" stroke="#6d3525" stroke-width="3"/><path d="M43 75q4-47 38-47 35 1 38 48-14-19-31-22-20 14-45 21" fill="${hair}"/><path d="M49 68q-3-39 31-42 34 2 38 41" fill="none" stroke="${hair}" stroke-width="8" stroke-linecap="round"/>${headwear}<path d="M65 86q5-4 10 0m11 0q5-4 10 0" fill="none" stroke="#3a2018" stroke-width="3" stroke-linecap="round"/><path d="M73 101q7 5 14 0" fill="none" stroke="#853d32" stroke-width="2.5" stroke-linecap="round"/><circle cx="80" cy="70" r="3" fill="#9d263b"/>${jewelry}${clothing}</svg>`)
}

function craftArtwork({ title, subtitle, background, accent, motif }: { title: string; subtitle: string; background: string; accent: string; motif: 'blockprint' | 'pottery' | 'loom' | 'dhokra' | 'pattachitra' | 'warli' | 'phulkari' | 'theyyam' | 'toys' | 'bamboo' | 'sungudi' | 'papier' | 'mask' | 'poetry' }) {
  const scenes: Record<typeof motif, string> = {
    blockprint: `<path d="M450 128l66 66-66 66-66-66zM450 158l36 36-36 36-36-36z" fill="none" stroke="${accent}" stroke-width="9"/><circle cx="450" cy="194" r="9" fill="${accent}"/><path d="M450 102v-24m0 232v-24m-126-92h-24m324 0h-24M360 104l18 18m144 144 18 18m0-180-18 18M378 266l-18 18" stroke="${accent}" stroke-width="8"/>`,
    pottery: `<path d="M390 123h120l-15 32 35 33-20 89q-60 54-120 0l-20-89 35-33z" fill="#f0d69a" stroke="${accent}" stroke-width="10"/><path d="M390 181q60 25 120 0M400 248q50-18 100 0" fill="none" stroke="${accent}" stroke-width="8"/><path d="M450 169c-20 24-20 38 0 44 20-6 20-20 0-44zm-25 60q25-25 50 0-25 25-50 0z" fill="${accent}"/>`,
    loom: `<path d="M340 98h220M350 100v190m200-190v190M330 290h240" stroke="${accent}" stroke-width="12"/><path d="M375 112v166m28-166v166m28-166v166m28-166v166m28-166v166m28-166v166m28-166v166" stroke="#f4dfae" stroke-width="7"/><path d="M360 155h180m-180 35h180m-180 35h180m-180 35h180" stroke="${accent}" stroke-width="8"/><path d="M385 155l22 35-22 35 22 35m90-105-22 35 22 35-22 35" fill="none" stroke="#8b1e2d" stroke-width="7"/>`,
    dhokra: `<path d="M450 112c-10 38-55 55-55 105a55 55 0 0 0 110 0c0-50-45-67-55-105z" fill="#d78a38" stroke="${accent}" stroke-width="9"/><path d="M407 195h86m-82 25h78m-70 25h62" stroke="#f5d38a" stroke-width="8"/><path d="M420 265q30 28 60 0" fill="none" stroke="${accent}" stroke-width="8"/><circle cx="430" cy="171" r="6" fill="#f5d38a"/><circle cx="470" cy="171" r="6" fill="#f5d38a"/>`,
    pattachitra: `<path d="M350 286q28-63 62-25 36-83 72-7 38-60 69 32z" fill="#248070"/><circle cx="450" cy="151" r="32" fill="#e5b343" stroke="${accent}" stroke-width="8"/><path d="M420 215q30-36 60 0v67h-60z" fill="#b63a39" stroke="${accent}" stroke-width="8"/><path d="M425 227h50m-50 17h50m-50 17h50" stroke="#f4dfae" stroke-width="5"/>`,
    warli: `<circle cx="450" cy="142" r="36" fill="none" stroke="#f5edd8" stroke-width="8"/><path d="M450 178v54m0-35-28 23m28-23 28 23m-28 12-20 29m20-29 20 29" fill="none" stroke="#f5edd8" stroke-width="8" stroke-linecap="round"/><path d="M380 276h140M390 260l18 16m104-16-18 16" stroke="${accent}" stroke-width="7"/>`,
    phulkari: `<path d="M450 106v176M360 194h180M386 130l128 128m0-128L386 258" stroke="#b83848" stroke-width="8"/><g fill="${accent}" stroke="#a92d44" stroke-width="5"><path d="M450 127c-42-31-51 15 0 35 51-20 42-66 0-35z"/><path d="M450 226c-42-31-51 15 0 35 51-20 42-66 0-35z"/><path d="M383 194c-31-42 15-51 35 0-20 51-66 42-35 0z"/><path d="M482 194c-31-42 15-51 35 0-20 51-66 42-35 0z"/></g>`,
    theyyam: `<circle cx="450" cy="163" r="35" fill="#c87938" stroke="${accent}" stroke-width="8"/><path d="M414 151q36-91 72 0l-11 13h-50z" fill="#b52f3c" stroke="#f5d378" stroke-width="7"/><path d="M450 107v-43m-29 53-24-34m82 34 24-34" stroke="#f5d378" stroke-width="8"/><path d="M420 208q30 28 60 0l28 76h-116z" fill="#b62d3f" stroke="${accent}" stroke-width="8"/>`,
    toys: `<path d="M390 245q-20-45 0-84t0-48h35q-18 40 0 80t0 52z" fill="#db9a37" stroke="${accent}" stroke-width="8"/><path d="M475 270q-18-39 0-73t0-74h35q-18 35 0 72t0 75z" fill="#bd3a45" stroke="${accent}" stroke-width="8"/><path d="M379 182h54m32-26h54m-54 80h54" stroke="#f6e4a8" stroke-width="8"/>`,
    bamboo: `<path d="M365 142h170l-22 132q-63 51-126 0z" fill="#cda65a" stroke="${accent}" stroke-width="10"/><path d="M380 163h140m-144 26h148m-152 26h156m-160 26h164m-160 24h156" stroke="#6d6e3b" stroke-width="7"/><path d="M394 147q56-89 112 0" fill="none" stroke="${accent}" stroke-width="11"/><path d="M400 149l95 118m-90-118L422 270m-22-121 70 121m60-121-95 118m90-118-69 121m69-121-48 121" stroke="#eed398" stroke-width="6"/>`,
    sungudi: `<path d="M350 112h200v164H350z" fill="#a83445" stroke="${accent}" stroke-width="9"/><path d="M366 128h168v132H366z" fill="#ecb958"/><g fill="#9a2639"><circle cx="386" cy="148" r="7"/><circle cx="426" cy="148" r="7"/><circle cx="466" cy="148" r="7"/><circle cx="506" cy="148" r="7"/><circle cx="406" cy="184" r="7"/><circle cx="446" cy="184" r="7"/><circle cx="486" cy="184" r="7"/><circle cx="386" cy="220" r="7"/><circle cx="426" cy="220" r="7"/><circle cx="466" cy="220" r="7"/><circle cx="506" cy="220" r="7"/><circle cx="406" cy="244" r="7"/><circle cx="446" cy="244" r="7"/><circle cx="486" cy="244" r="7"/></g>`,
    papier: `<path d="M378 125q72-35 144 0l-12 146q-60 35-120 0z" fill="#e9d4aa" stroke="${accent}" stroke-width="10"/><path d="M394 151q56-27 112 0m-110 27q54-27 108 0m-106 27q52-27 104 0" fill="none" stroke="#26726a" stroke-width="7"/><path d="M450 157c-34-27-44 12 0 30 44-18 34-57 0-30zm0 57c-34-27-44 12 0 30 44-18 34-57 0-30z" fill="#a83343"/>`,
    mask: `<path d="M380 110q70-38 140 0l-8 127q-62 72-124 0z" fill="#f3d69a" stroke="${accent}" stroke-width="10"/><path d="M395 162q20-19 40 0m30 0q20-19 40 0" fill="none" stroke="#392040" stroke-width="9"/><path d="M420 204q30 27 60 0" fill="none" stroke="#a32d43" stroke-width="9"/><path d="M405 119l-18-35m48 25-4-44m40 44 7-44m31 54 20-35" stroke="${accent}" stroke-width="9"/>`,
    poetry: `<path d="M406 264V160q45-48 90 0v104m-116-96h142M428 137v-28m23 20V91m23 18V81" fill="none" stroke="${accent}" stroke-width="10" stroke-linecap="round"/><path d="M399 264h104" stroke="#8b1e2d" stroke-width="12"/><circle cx="385" cy="116" r="10" fill="#a62b45"/><circle cx="520" cy="108" r="8" fill="#08796f"/><path d="M365 150q14-17 28 0t28 0m80 32q14-17 28 0t28 0" fill="none" stroke="#9d263b" stroke-width="6"/>`,
  }
  return svgImage(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 500"><defs><linearGradient id="bg" x2="0" y2="1"><stop stop-color="${background}"/><stop offset="1" stop-color="#f7e5bc"/></linearGradient><pattern id="border" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M0 0h28v28H0z" fill="none" stroke="${accent}" stroke-width="3"/><path d="M14 3l11 11-11 11L3 14z" fill="none" stroke="${accent}" stroke-width="2"/></pattern></defs><rect width="900" height="500" fill="url(#bg)"/><path d="M0 0h900v36H0zm0 464h900v36H0z" fill="url(#border)"/><circle cx="450" cy="194" r="153" fill="#fff7dc" fill-opacity=".72" stroke="${accent}" stroke-width="8"/><circle cx="450" cy="194" r="137" fill="none" stroke="${accent}" stroke-width="2" stroke-dasharray="5 8"/>${scenes[motif]}<text x="450" y="382" text-anchor="middle" fill="#421a25" font-family="Georgia,serif" font-size="38" font-weight="bold">${title}</text><text x="450" y="423" text-anchor="middle" fill="#684b38" font-family="Arial,sans-serif" font-size="21" letter-spacing="3">${subtitle}</text><path d="M92 251q24-25 48 0t48 0m526 0q24-25 48 0t48 0" fill="none" stroke="${accent}" stroke-width="5"/></svg>`)
}

const portraitOptions = {
  mira: { skin:'#a85f3b', hair:'#24151a', garment:'#a82d45', accent:'#e5b54b', style:'sari' as const },
  ananya: { skin:'#c37a50', hair:'#24151a', garment:'#08796f', accent:'#efc96b', style:'dupatta' as const },
  aarav: { skin:'#ad6847', hair:'#261b18', garment:'#39476d', accent:'#d9a63b', style:'kurta' as const },
  saira: { skin:'#925238', hair:'#201419', garment:'#55204b', accent:'#e6bd54', style:'dupatta' as const },
  ghafur: { skin:'#8d5338', hair:'#241915', garment:'#08796f', accent:'#e1ad48', style:'turban' as const },
}

export const photos = {
  mira: portrait(portraitOptions.mira),
  ananya: portrait(portraitOptions.ananya),
  aarav: portrait(portraitOptions.aarav),
  saira: portrait(portraitOptions.saira),
  ghafur: portrait(portraitOptions.ghafur),
  portrait1: portrait(portraitOptions.ananya),
  portrait2: portrait(portraitOptions.aarav),
  collective: craftArtwork({ title:'Kutch Craft Collective', subtitle:'GUJARAT · COMMUNITY', background:'#e8c777', accent:'#8b1e2d', motif:'blockprint' }),
  archive: craftArtwork({ title:'Astitva Archive', subtitle:'INDIA · LIVING HERITAGE', background:'#d8bd79', accent:'#39476d', motif:'pattachitra' }),
  loom: craftArtwork({ title:'Handloom Stories', subtitle:'BHUJODI · KUTCH', background:'#d6b272', accent:'#08796f', motif:'loom' }),
  indigo: craftArtwork({ title:'Ajrakh Printing', subtitle:'DHAMADKA · GUJARAT', background:'#243a66', accent:'#a62b45', motif:'blockprint' }),
  pottery: craftArtwork({ title:'Blue Pottery', subtitle:'JAIPUR · RAJASTHAN', background:'#90bdc5', accent:'#215b78', motif:'pottery' }),
  dhokra: craftArtwork({ title:'Dhokra Metalwork', subtitle:'BASTAR · CHHATTISGARH', background:'#d69549', accent:'#693c29', motif:'dhokra' }),
  pattachitra: craftArtwork({ title:'Pattachitra', subtitle:'ODISHA · PAINTED STORIES', background:'#e5bc72', accent:'#9a2e32', motif:'pattachitra' }),
  warli: craftArtwork({ title:'Warli Art', subtitle:'DAHANU · MAHARASHTRA', background:'#75674d', accent:'#392b24', motif:'warli' }),
  phulkari: craftArtwork({ title:'Phulkari', subtitle:'PUNJAB · SILK EMBROIDERY', background:'#e2a86f', accent:'#a42c47', motif:'phulkari' }),
  theyyam: craftArtwork({ title:'Theyyam', subtitle:'KANNUR · KERALA', background:'#c76538', accent:'#50213d', motif:'theyyam' }),
  channapatna: craftArtwork({ title:'Channapatna Toys', subtitle:'KARNATAKA · LACQUER CRAFT', background:'#e4c169', accent:'#9d3b30', motif:'toys' }),
  bamboo: craftArtwork({ title:'Bamboo Weaving', subtitle:'MAJULI · ASSAM', background:'#b7b579', accent:'#5b4932', motif:'bamboo' }),
  sungudi: craftArtwork({ title:'Sungudi Textiles', subtitle:'MADURAI · TAMIL NADU', background:'#d9a64d', accent:'#873447', motif:'sungudi' }),
  papier: craftArtwork({ title:'Kashmiri Papier-Mache', subtitle:'KASHMIR · HAND PAINTED', background:'#d6bd82', accent:'#26726a', motif:'papier' }),
  mask: craftArtwork({ title:'Satra Mask Making', subtitle:'MAJULI · ASSAM', background:'#d6ae6f', accent:'#54224a', motif:'mask' }),
  doharo: craftArtwork({ title:'Gujarati Doharo', subtitle:'GUJARATI · ORAL POETRY', background:'#d8bd79', accent:'#39476d', motif:'poetry' }),
}
export const profiles: Profile[] = [
  { id:'mira', name:'Mira Vankar', handle:'@miravankar', role:'Artisan', bio:'Ajrakh printer and natural-dye maker from Dhamadka. I share the block-printing practice, plant colours and stories my family has carried across generations.', region:'Dhamadka, Kutch · Gujarat', language:'Kutchi · Gujarati', avatar:photos.mira, verified:true, followers:1284, following:286 },
  { id:'ananya', name:'Ananya Rao', handle:'@ananyarao', role:'Explorer', bio:'A Bengaluru traveller collecting the stories behind India’s textiles, foodways and living traditions—with makers’ voices at the centre.', region:'Bengaluru · Karnataka', language:'Kannada · English', avatar:photos.ananya, verified:false, followers:418, following:301 },
  { id:'aarav', name:'Aarav Mehta', handle:'@aaravfieldnotes', role:'Student / Researcher', bio:'Ahmedabad-based graduate researcher documenting community-led craft knowledge with consent, regional-language notes and citations.', region:'Ahmedabad · Gujarat', language:'Gujarati · Hindi · English', avatar:photos.aarav, verified:false, followers:236, following:178 },
  { id:'saira', name:'Saira Bano', handle:'@sairabano', role:'Expert / Evaluator', bio:'Ajrakh practitioner and community-appointed reviewer from Kutch. I help keep local names, techniques and oral histories in context.', region:'Dhamadka, Kutch · Gujarat', language:'Kutchi · Gujarati · Hindi', avatar:photos.saira, verified:true, followers:2093, following:402 },
  { id:'ghafur', name:'Ghafur Haji', handle:'@ghafurji', role:'Cultural Knowledge Holder', bio:'Kutchi storyteller and language keeper from Nirona. I share community memory and review oral accounts with local context.', region:'Nirona · Kutch · Gujarat', language:'Kutchi · Gujarati', avatar:photos.ghafur, verified:true, followers:875, following:129 },
  { id:'collective', name:'Kutch Craft Collective', handle:'Community page', role:'Institution / NGO', bio:'A community-led network in Bhuj connecting Kutch makers, cultural organisations and visitors through locally shared craft stories.', region:'Bhuj · Gujarat', language:'Gujarati · Hindi', avatar:photos.collective, verified:true, followers:3420, following:617 },
  { id:'archive', name:'Astitva Heritage Archive', handle:'@astitvaarchive', role:'Admin / Moderator', bio:'A community archive for India’s living traditions, regional-language maker voices and place-based cultural knowledge.', region:'India', language:'Regional languages', avatar:photos.archive, verified:true, followers:8410, following:51 },
  { id:'raghav', name:'Raghav Kumhar', handle:'@raghavkumhar', role:'Artisan', bio:'Jaipur potter sharing the mineral colours, kiln practice and workshop stories behind blue pottery.', region:'Jaipur · Rajasthan', language:'Hindi · Rajasthani', avatar:portrait({ skin:'#a96442', hair:'#241915', garment:'#315f79', accent:'#ddb34e', style:'kurta' }), verified:true, followers:692, following:214 },
  { id:'mangi', name:'Mangi Bai Netam', handle:'@mangibaibastar', role:'Cultural Knowledge Holder', bio:'A Bastar community storyteller sharing the local context of Dhokra metalwork and its making traditions.', region:'Kondagaon · Chhattisgarh', language:'Gondi · Hindi', avatar:portrait({ skin:'#9c5b3d', hair:'#241915', garment:'#a4333c', accent:'#e2b34d', style:'sari' }), verified:true, followers:934, following:188 },
  { id:'lakshmi', name:'Lakshmi Nayak', handle:'@lakshmipattachitra', role:'Artisan', bio:'Pattachitra painter from Raghurajpur sharing brushwork, natural colours and stories from Odisha’s painting tradition.', region:'Raghurajpur · Odisha', language:'Odia · Hindi', avatar:portrait({ skin:'#a76140', hair:'#24151a', garment:'#a72d45', accent:'#e1b54b', style:'sari' }), verified:true, followers:1106, following:247 },
  { id:'rohini', name:'Rohini Wagh', handle:'@rohiniwarli', role:'Cultural Knowledge Holder', bio:'Warli artist and community knowledge holder from Dahanu, sharing the meaning and context of village painting traditions.', region:'Dahanu · Maharashtra', language:'Warli · Marathi', avatar:portrait({ skin:'#95573c', hair:'#261816', garment:'#8c633d', accent:'#f0dca9', style:'sari' }), verified:true, followers:781, following:163 },
  { id:'harpreet', name:'Harpreet Kaur', handle:'@harpreetphulkari', role:'Artisan', bio:'Patiala embroiderer sharing Phulkari stitch patterns, cloth and the family occasions for which each piece is made.', region:'Patiala · Punjab', language:'Punjabi · Hindi', avatar:portrait({ skin:'#a76647', hair:'#211619', garment:'#b43148', accent:'#e5bb52', style:'dupatta' }), verified:true, followers:1352, following:298 },
  { id:'kannan', name:'Kannan Perumal', handle:'@kannantheyyam', role:'Cultural Knowledge Holder', bio:'Kannur-based community knowledge holder sharing context around Theyyam performance, ritual and costume traditions.', region:'Kannur · Kerala', language:'Malayalam', avatar:portrait({ skin:'#97583b', hair:'#241719', garment:'#9e2a38', accent:'#e4b744', style:'kurta' }), verified:true, followers:1204, following:251 },
  { id:'chandru', name:'Chandru M.', handle:'@chandruwoodcraft', role:'Artisan', bio:'Channapatna toy maker sharing wood turning, lac colouring and workshop practice from Karnataka.', region:'Channapatna · Karnataka', language:'Kannada', avatar:portrait({ skin:'#a65f3e', hair:'#241916', garment:'#28756c', accent:'#e3b84a', style:'kurta' }), verified:true, followers:863, following:192 },
  { id:'bipul', name:'Bipul Das', handle:'@bipulmajuli', role:'Artisan', bio:'Majuli mask maker sharing materials, shaping techniques and the performance traditions connected to satra masks.', region:'Majuli · Assam', language:'Assamese · Hindi', avatar:portrait({ skin:'#ad6b49', hair:'#241a18', garment:'#3f526e', accent:'#e1b74f', style:'kurta' }), verified:true, followers:973, following:206 },
  { id:'meenakshi', name:'Meenakshi Sundaram', handle:'@meenakshisungudi', role:'Artisan', bio:'Madurai textile maker sharing Sungudi tie-dye, its dotted patterns and the city’s cloth-making traditions.', region:'Madurai · Tamil Nadu', language:'Tamil', avatar:portrait({ skin:'#a45e40', hair:'#23151a', garment:'#a32d42', accent:'#e2b84f', style:'sari' }), verified:true, followers:902, following:218 },
  { id:'zaina', name:'Zaina Bhat', handle:'@zainapapier', role:'Artisan', bio:'Srinagar papier-mâché painter sharing paper preparation, hand-painted motifs and finishing practice.', region:'Srinagar · Jammu and Kashmir', language:'Kashmiri · Urdu', avatar:portrait({ skin:'#bf805e', hair:'#25171c', garment:'#426b69', accent:'#d9ae4e', style:'dupatta' }), verified:true, followers:1178, following:278 },
]
export const profileForRole = (role: Role) => profiles.find(profile => profile.role === role) || profiles[1]

export const sampleCommunityPosts: CommunityPost[] = [
  { id:'post-indigo', kind:'photo', nativeTitle:'અજરખની છાપ', englishTitle:'Ajrakh · indigo in layers', caption:'The resist blocks come out before dawn, while the air is still cool. Each layer needs its own drying time.', craft:'Ajrakh printing', location:'Dhamadka, Kutch · Gujarat', mediaUrl:photos.indigo, filename:'indigo-blocks.jpg', authorId:'mira', hashtags:['#Ajrakh','#NaturalDye','#Kutch'], createdAt:'2026-09-29T07:30:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-pottery-story', kind:'story', nativeTitle:'नीली मिट्टी की कहानी', englishTitle:'Blue pottery · Jaipur', caption:'A Jaipur studio note: mineral pigments and careful glaze firing give blue pottery its distinctive colours and floral forms.', craft:'Blue pottery', location:'Jaipur · Rajasthan', mediaUrl:photos.pottery, filename:'jaipur-pottery.jpg', authorId:'raghav', hashtags:['#BluePottery','#Jaipur'], createdAt:'2026-09-29T11:10:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-fieldwork', kind:'photo', nativeTitle:'વણકરનું તાણું', englishTitle:'Vankar handloom · Kutch', caption:'Field note: recorded with maker consent. This loom vocabulary is written in Gujarati first, then translated with the speaker.', craft:'Vankar handloom', location:'Bhujodi, Kutch · Gujarat', mediaUrl:photos.loom, filename:'loom-fieldnote.jpg', authorId:'aarav', hashtags:['#FieldNotes','#Handloom','#Gujarati'], createdAt:'2026-09-28T14:15:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-bastar-story', kind:'story', nativeTitle:'ढोकरा शिल्प', englishTitle:'Dhokra · lost-wax casting', caption:'Bastar’s lost-wax metalwork begins with a hand-shaped wax model, built up with fine coils before the clay mould is fired.', craft:'Dhokra metalwork', location:'Bastar · Chhattisgarh', mediaUrl:photos.dhokra, filename:'dhokra.jpg', authorId:'mangi', hashtags:['#Dhokra','#Bastar','#LivingHeritage'], createdAt:'2026-09-28T08:20:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-pattachitra', kind:'photo', nativeTitle:'ପଟ୍ଟଚିତ୍ର', englishTitle:'Pattachitra · painted stories', caption:'Pattachitra artists build each scene with fine outlines, traditional colours and story details passed through Odisha’s painting communities.', craft:'Pattachitra painting', location:'Raghurajpur · Odisha', mediaUrl:photos.pattachitra, filename:'pattachitra-story.jpg', authorId:'lakshmi', hashtags:['#Pattachitra','#Odisha','#LivingArt'], createdAt:'2026-09-27T10:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-warli', kind:'story', nativeTitle:'वारली चित्रकला', englishTitle:'Warli · stories in white', caption:'Warli painting uses circles, triangles and lines to show village life, farming, celebration and the relationship between people and nature.', craft:'Warli painting', location:'Dahanu · Maharashtra', mediaUrl:photos.warli, filename:'warli-painting.jpg', authorId:'rohini', hashtags:['#Warli','#Maharashtra','#AdivasiArt'], createdAt:'2026-09-26T09:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-phulkari', kind:'photo', nativeTitle:'ਫੁਲਕਾਰੀ', englishTitle:'Phulkari · flowers in thread', caption:'Bright silk floss forms counted floral stitches on khaddar cloth. Phulkari is made for family celebrations and worn close to the heart.', craft:'Phulkari embroidery', location:'Patiala · Punjab', mediaUrl:photos.phulkari, filename:'phulkari.jpg', authorId:'harpreet', hashtags:['#Phulkari','#Punjab','#Embroidery'], createdAt:'2026-09-25T12:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-baulsong', kind:'audio', mediaType:'audio', nativeTitle:'ગુજરાતી દોહરો', englishTitle:'Doharo chhand · Gujarat', caption:'A Gujarati Doharo verse carries its rhythm through a distinctive metre. Listen to the recording and explore the language and poetic form with community context.', craft:'Gujarati oral poetry', location:'Gujarat · Western India', mediaUrl:'https://upload.wikimedia.org/wikipedia/commons/d/d7/Doharo.ogg', filename:'doharo-recording.ogg', authorId:'saira', hashtags:['#Gujarati','#Doharo','#OralTradition'], createdAt:'2026-09-24T08:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-theyyam', kind:'photo', nativeTitle:'തെയ്യം', englishTitle:'Theyyam · ritual performance', caption:'Theyyam brings together a performer, elaborate headgear, music and ritual knowledge held by communities in North Kerala.', craft:'Theyyam performance', location:'Kannur · Kerala', mediaUrl:photos.theyyam, filename:'theyyam-performance.jpg', authorId:'kannan', hashtags:['#Theyyam','#Kerala','#LivingRitual'], createdAt:'2026-09-23T07:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-channapatna', kind:'story', nativeTitle:'ಚನ್ನಪಟ್ಟಣದ ಗೊಂಬೆಗಳು', englishTitle:'Channapatna · lacquer toys', caption:'Turned wood spins against a lac stick before colour follows the grain. Channapatna’s lacquer toys carry the skill of Karnataka’s toy-making workshops.', craft:'Channapatna toy making', location:'Channapatna · Karnataka', mediaUrl:photos.channapatna, filename:'lacquer-toys.jpg', authorId:'chandru', hashtags:['#Channapatna','#Karnataka','#ToyMaking'], createdAt:'2026-09-22T11:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
  { id:'post-bamboo', kind:'photo', nativeTitle:'बाँस की बुनाई', englishTitle:'Bamboo weaving · Assam', caption:'Split bamboo becomes a basket through an understanding of tension, moisture and shape. Weavers in Majuli pass this knowledge hand to hand.', craft:'Bamboo weaving', location:'Majuli · Assam', mediaUrl:photos.bamboo, filename:'bamboo-weaving.jpg', authorId:'bipul', hashtags:['#BambooCraft','#Assam','#NortheastIndia'], createdAt:'2026-09-21T06:00:00.000Z', claimType:'community', verificationStatus:'not-required' },
]
export const sampleProducts: ProductListing[] = [
  { id: 'ajrak-1', title: 'Ajrakh indigo stole', craft: 'Block print · Natural dye', qualities: 'Hand block-printed, plant-dyed, breathable cotton', heritage: 'Printed in Dhamadka using resist blocks and indigo knowledge passed through generations.', price: '2400', location: 'Dhamadka, Kutch, Gujarat', stock: '4', image: photos.indigo, maker: 'Mira Vankar' },
  { id: 'pottery-1', title: 'Blue pottery serving bowl', craft: 'Blue pottery · Glazed ceramic', qualities: 'Hand-shaped, mineral pigment, lead-free glaze', heritage: 'Made with Jaipur’s quartz-based blue pottery technique and floral forms from the old city.', price: '1850', location: 'Jaipur, Rajasthan', stock: '8', image: photos.pottery, maker: 'Raghav Kumhar' },
  { id: 'shawl-1', title: 'Kala cotton handwoven shawl', craft: 'Handloom · Kutch', qualities: 'Rain-fed native cotton, naturally textured, handwoven', heritage: 'Woven in Bhujodi with local kala cotton and the Vankar community’s loom practice.', price: '5800', location: 'Bhujodi, Kutch, Gujarat', stock: 'Made to order', image: photos.loom, maker: 'Vankar collective' },
  { id: 'banarasi-1', title: 'Handwoven brocade runner', craft: 'Handloom · Brocade', qualities: 'Silk blend, handloom woven, zari border', heritage: 'A small-format brocade piece woven in Varanasi. Listing is a maker sample, not a claim of GI certification.', price: '3200', location: 'Varanasi, Uttar Pradesh', stock: '3', image: photos.loom, maker: 'Weaver family collective' },
  { id: 'dhokra-1', title: 'Lost-wax brass diya pair', craft: 'Metalwork · Dhokra', qualities: 'Hand cast, beeswax detailing, brass', heritage: 'A contemporary diya pair made with lost-wax casting knowledge shared by Bastar makers.', price: '1450', location: 'Kondagaon, Bastar, Chhattisgarh', stock: '6', image: photos.dhokra, maker: 'Bastar artisan group' },
  { id: 'madurai-1', title: 'Sungudi cotton table cloth', craft: 'Textile · Tie-dye', qualities: 'Cotton, hand-tied dots, natural palette', heritage: 'Sungudi-inspired dotted cotton from a Madurai maker collective; technique and maker details are shared with the listing.', price: '2100', location: 'Madurai, Tamil Nadu', stock: '5', image: photos.sungudi, maker: 'Meenakshi Sundaram' },
  { id: 'papier-1', title: 'Hand-painted papier-mâché box', craft: 'Papier-mâché · Painting', qualities: 'Paper pulp, hand painted, floral design', heritage: 'A small storage box painted in a Kashmir workshop. The maker describes the preparation and finishing steps.', price: '980', location: 'Srinagar, Jammu and Kashmir', stock: '7', image: photos.papier, maker: 'Zaina Bhat' },
  { id: 'mask-1', title: 'Satriya performance mask', craft: 'Mask making · Papier-mâché', qualities: 'Paper pulp, natural fibre, hand finished', heritage: 'A performance mask inspired by Majuli’s satra mask-making traditions, described by its maker.', price: '2600', location: 'Majuli, Assam', stock: 'Made to order', image: photos.mask, maker: 'Bipul Das' },
]

export function refreshSamplePosts(posts: CommunityPost[]) {
  const samples = new Map(sampleCommunityPosts.map(post => [post.id, post]))
  return posts.map(post => {
    const sample = samples.get(post.id)
    return sample ? { ...post, ...sample, verificationStatus: post.verificationStatus } : post
  })
}

export function refreshSampleProducts(products: ProductListing[]) {
  const samples = new Map(sampleProducts.map(product => [product.id, product]))
  return products.map(product => {
    const sample = samples.get(product.id)
    return sample ? { ...product, ...sample } : product
  })
}
